
CREATE TABLE ANEXOS(
	ANEX_RADI_NUME bigint NOT NULL,
	ANEX_CODIGO varchar(20)  NOT NULL,
	ANEX_TIPO smallint NULL,
	ANEX_TAMANO int NULL,
	ANEX_SOLO_LECT varchar(1)  NULL,
	ANEX_CREADOR varchar(20)  NULL,
	ANEX_DESC varchar(512)  NULL,
	ANEX_NUMERO int NULL,
	ANEX_NOMB_ARCHIVO varchar(50)  NULL,
	ANEX_BORRADO varchar(1)  NULL,
	ANEX_ORIGEN tinyint NOT NULL DEFAULT ((0)),
	ANEX_UBIC varchar(15)  NULL,
	ANEX_SALIDA tinyint NOT NULL DEFAULT ((0)),
	RADI_NUME_SALIDA bigint NULL,
	ANEX_RADI_FECH datetime NULL,
	ANEX_ESTADO tinyint NOT NULL DEFAULT ((0)),
	USUA_DOC varchar(14)  NULL,
	SGD_REM_DESTINO tinyint NOT NULL DEFAULT ((0)),
	ANEX_FECH_ENVIO datetime NULL,
	SGD_DIR_TIPO smallint NULL,
	ANEX_FECH_IMPRES datetime NULL,
	ANEX_DEPE_CREADOR smallint NULL,
	SGD_DOC_SECUENCIA bigint NULL,
	SGD_DOC_PADRE varchar(20)  NULL,
	SGD_ARG_CODIGO tinyint NULL,
	SGD_TPR_CODIGO smallint NULL,
	SGD_DEVE_CODIGO tinyint NULL,
	SGD_DEVE_FECH datetime NULL,
	SGD_FECH_IMPRES datetime NULL,
	ANEX_FECH_ANEX datetime NULL,
	ANEX_DEPE_CODI varchar(3)  NULL,
	SGD_PNUFE_CODI smallint NULL,
	SGD_DNUFE_CODI smallint NULL,
	ANEX_USUDOC_CREADOR varchar(15)  NULL,
	SGD_FECH_DOC datetime NULL,
	SGD_APLI_CODI smallint NULL,
	SGD_TRAD_CODIGO tinyint NULL,
	SGD_DIR_DIRECCION varchar(150)  NULL,
	MUNI_CODI smallint NULL,
	DPTO_CODI smallint NULL,
	SGD_EXP_NUMERO varchar(18)  NULL,
        CONSTRAINT ANEX_CODIGO PRIMARY KEY(ANEX_CODIGO)
)

CREATE TABLE ANEXOS_HISTORICO(
	ANEX_HIST_ANEX_CODI varchar(20)  NOT NULL,
	ANEX_HIST_NUM_VER smallint NOT NULL,
	ANEX_HIST_TIPO_MOD varchar(2)  NOT NULL,
	ANEX_HIST_USUA varchar(15)  NOT NULL,
	ANEX_HIST_FECHA datetime NOT NULL,
	USUA_DOC varchar(14)  NULL,
        CONSTRAINT PK_ANEX_CODI_NUM_VER PRIMARY KEY (ANEX_HIST_ANEX_CODI ,ANEX_HIST_NUM_VER )
) 


CREATE TABLE ANEXOS_TIPO(
	ANEX_TIPO_CODI smallint NOT NULL,
	ANEX_TIPO_EXT varchar(10)  NOT NULL,
	ANEX_TIPO_DESC varchar(50)  NULL,
        CONSTRAINT PK_ANEX_TIPO_CODI PRIMARY KEY (ANEX_TIPO_CODI)
) 


CREATE TABLE BODEGA_EMPRESAS(
	NOMBRE_DE_LA_EMPRESA varchar(160)  NULL,
	NUIR varchar(13)  NULL,
	NIT_DE_LA_EMPRESA varchar(80)  NULL,
	SIGLA_DE_LA_EMPRESA varchar(80)  NULL,
	DIRECCION varchar(80)  NULL,
	CODIGO_DEL_DEPARTAMENTO smallint NULL,
	CODIGO_DEL_MUNICIPIO smallint NULL,
	TELEFONO_1 varchar(15)  NULL,
	TELEFONO_2 varchar(15)  NULL,
	EMAIL varchar(50)  NULL,
	NOMBRE_REP_LEGAL varchar(72)  NULL,
	CARGO_REP_LEGAL varchar(50)  NULL,
	IDENTIFICADOR_EMPRESA int NOT NULL,
	ARE_ESP_SECUE int NOT NULL,
	ID_CONT tinyint NOT NULL DEFAULT ((1)),
	ID_PAIS smallint NOT NULL DEFAULT ((170)),
	ACTIVA tinyint NOT NULL DEFAULT ((1)),
	FLAG_RUPS varchar(1)  NULL,
        PRIMARY KEY(IDENTIFICADOR_EMPRESA )
)


CREATE TABLE CARPETA(
	CARP_CODI tinyint NOT NULL,
	CARP_DESC varchar(80)  NOT NULL,
        PRIMARY KEY (CARP_CODI )
)

CREATE TABLE CARPETA_PER(
	USUA_CODI smallint NOT NULL,
	DEPE_CODI smallint NOT NULL,
	NOMB_CARP varchar(30)  NULL,
	DESC_CARP varchar(30)  NULL,
	CODI_CARP smallint NOT NULL,
        PRIMARY KEY (USUA_CODI ,DEPE_CODI ,CODI_CARP )
)

CREATE TABLE DEPARTAMENTO(
	ID_CONT tinyint NOT NULL DEFAULT ((1)),
	ID_PAIS smallint NOT NULL DEFAULT ((170)),
	DPTO_CODI smallint NOT NULL,
	DPTO_NOMB varchar(70)  NOT NULL,
        PRIMARY KEY (ID_CONT ,ID_PAIS ,	DPTO_CODI )
)

CREATE TABLE DEPENDENCIA(
	DEPE_CODI smallint NOT NULL,
	DEPE_NOMB varchar(70)  NOT NULL,
	DPTO_CODI smallint NULL,
	DEPE_CODI_PADRE smallint NULL,
	MUNI_CODI smallint NULL,
	DEPE_CODI_TERRITORIAL smallint NULL,
	DEP_SIGLA varchar(100)  NULL,
	DEP_CENTRAL smallint NULL,
	DEP_DIRECCION varchar(100)  NULL,
	DEPE_NUM_INTERNA smallint NULL,
	DEPE_NUM_RESOLUCION smallint NULL,
	DEPE_RAD_TP1 smallint NULL,
	DEPE_RAD_TP2 smallint NULL,
	ID_CONT tinyint NOT NULL DEFAULT ((1)),
	ID_PAIS smallint NOT NULL DEFAULT ((170)),
	DEPE_ESTADO tinyint NOT NULL DEFAULT ((1)),
	DEPE_RAD_TP3 smallint NULL,
        PRIMARY KEY (DEPE_CODI )
)

CREATE TABLE DEPENDENCIA_VISIBILIDAD(
	CODIGO_VISIBILIDAD bigint NOT NULL,
	DEPENDENCIA_VISIBLE smallint NOT NULL,
	DEPENDENCIA_OBSERVA smallint NOT NULL,
        PRIMARY KEY (CODIGO_VISIBILIDAD )
)

CREATE TABLE ESTADO(
	ESTA_CODI tinyint NOT NULL,
	ESTA_DESC varchar(100)  NOT NULL,
        PRIMARY KEY (ESTA_CODI )
)


CREATE TABLE HIST_EVENTOS(
	DEPE_CODI smallint NOT NULL,
	HIST_FECH datetime NOT NULL,
	USUA_CODI bigint NOT NULL,
	RADI_NUME_RADI bigint NOT NULL,
	HIST_OBSE varchar(600)  NOT NULL,
	USUA_CODI_DEST bigint NULL,
	USUA_DOC varchar(14)  NULL,
	USUA_DOC_OLD varchar(15)  NULL,
	SGD_TTR_CODIGO smallint NULL,
	HIST_USUA_AUTOR varchar(14)  NULL,
	HIST_DOC_DEST varchar(14)  NULL,
	DEPE_CODI_DEST smallint NULL
)

CREATE TABLE INFORMADOS(
	RADI_NUME_RADI bigint NOT NULL,
	USUA_CODI bigint NOT NULL,
	DEPE_CODI smallint NOT NULL,
	INFO_DESC varchar(600)  NULL,
	INFO_FECH datetime NOT NULL,
	INFO_LEIDO tinyint NOT NULL DEFAULT ((0)),
	USUA_CODI_INFO smallint NULL,
	INFO_CODI varchar(14) NULL,
	USUA_DOC varchar(14)  NULL
)


CREATE TABLE MEDIO_RECEPCION(
	MREC_CODI tinyint NOT NULL,
	MREC_DESC varchar(100)  NOT NULL,
        MREC_ENV  smallint DEFAULT ((0)),
        MREC_REC  smallint DEFAULT ((0)),
        MREC_PQR  smallint DEFAULT ((0)),
        ENVIO_DIRECTO smallint DEFAULT ((0)),
        PRIMARY KEY(MREC_CODI)
)

CREATE TABLE SGD_MTR_MRECFENV
(
    MREC_CODI integer NOT NULL,
    SGD_FENV_CODIGO integer NOT NULL,
    CONSTRAINT pk_mrecfenv PRIMARY KEY (MREC_CODI, SGD_FENV_CODIGO),
    CONSTRAINT uk_fenv UNIQUE (SGD_FENV_CODIGO),
    CONSTRAINT uk_mrec UNIQUE (MREC_CODI)
);

CREATE TABLE MUNICIPIO(
	ID_CONT tinyint NOT NULL,
	ID_PAIS smallint NOT NULL,
	DPTO_CODI smallint NOT NULL,
	MUNI_CODI smallint NOT NULL,
	MUNI_NOMB varchar(100)  NOT NULL,
	HOMOLOGA_MUNI varchar(10)  NULL,
	HOMOLOGA_IDMUNI smallint NULL,
	ACTIVA tinyint NOT NULL DEFAULT ((1)),
        PRIMARY KEY (ID_CONT ,ID_PAIS ,DPTO_CODI ,MUNI_CODI )
)

CREATE TABLE PAR_SERV_SERVICIOS(
	PAR_SERV_SECUE int NOT NULL,
	PAR_SERV_CODIGO varchar(5)  NULL,
	PAR_SERV_NOMBRE varchar(100)  NULL,
	PAR_SERV_ESTADO varchar(1)  NULL,
        PRIMARY KEY (PAR_SERV_SECUE )
)

CREATE TABLE PRESTAMO(
	PRES_ID bigint NOT NULL,
	RADI_NUME_RADI bigint,
	USUA_LOGIN_ACTU varchar(20)  NOT NULL,
	DEPE_CODI smallint NOT NULL,
	USUA_LOGIN_PRES varchar(20)  NULL,
	PRES_DESC varchar(200)  NULL,
	PRES_FECH_PRES datetime NULL,
	PRES_FECH_DEVO datetime NULL,
	PRES_FECH_PEDI datetime NOT NULL,
	PRES_ESTADO tinyint NULL,
	PRES_REQUERIMIENTO tinyint NULL,
	PRES_DEPE_ARCH smallint NULL,
	PRES_FECH_VENC datetime NULL,
	DEV_DESC varchar(500)  NULL,
	PRES_FECH_CANC datetime NULL,
	USUA_LOGIN_CANC varchar(20)  NULL,
	USUA_LOGIN_RX varchar(20)  NULL,
        SGD_EXP_NUMERO varchar(18 ),
        SGD_CARPETA_ID int,
        PRES_FECH_RENOVACION1 DATETIME,
        CANC_DESC VARCHAR(200)
        PRIMARY KEY(PRES_ID )
)

CREATE TABLE RADICADO(
	RADI_NUME_RADI bigint NOT NULL,
	RADI_FECH_RADI datetime NOT NULL,
	TDOC_CODI smallint NOT NULL,
	TRTE_CODI tinyint NULL,
	MREC_CODI tinyint NULL,
	EESP_CODI bigint NULL,
	EOTRA_CODI bigint NULL,
	RADI_TIPO_EMPR varchar(2)  NULL,
	RADI_FECH_OFIC datetime NULL,
	TDID_CODI tinyint NULL,
	RADI_NUME_IDEN varchar(15)  NULL,
	RADI_NOMB varchar(90)  NULL,
	RADI_PRIM_APEL varchar(50)  NULL,
	RADI_SEGU_APEL varchar(50)  NULL,
	RADI_PAIS varchar(70)  NULL,
	MUNI_CODI smallint NULL,
	CPOB_CODI smallint NULL,
	CARP_CODI smallint NULL,
	ESTA_CODI tinyint NULL,
	DPTO_CODI smallint NULL,
	CEN_MUNI_CODI smallint NULL,
	CEN_DPTO_CODI smallint NULL,
	RADI_DIRE_CORR varchar(100)  NULL,
	RADI_TELE_CONT bigint NULL,
	RADI_NUME_HOJA smallint NULL,
	RADI_DESC_ANEX varchar(100)  NULL,
	RADI_NUME_DERI bigint NULL,
	RADI_PATH varchar(100)  NULL,
	RADI_USUA_ACTU bigint NULL,
	RADI_DEPE_ACTU smallint NULL,
	RADI_FECH_ASIG datetime NULL,
	RADI_ARCH1 varchar(10)  NULL,
	RADI_ARCH2 varchar(10)  NULL,
	RADI_ARCH3 varchar(10)  NULL,
	RADI_ARCH4 varchar(10)  NULL,
	RA_ASUN varchar(350)  NULL,
	RADI_USU_ANTE varchar(45)  NULL,
	RADI_DEPE_RADI smallint NULL,
	RADI_REM varchar(60)  NULL,
	RADI_USUA_RADI bigint NULL,
	CODI_NIVEL tinyint NOT NULL DEFAULT ((1)),
	FLAG_NIVEL int NOT NULL DEFAULT ((1)),
	CARP_PER tinyint NOT NULL DEFAULT ((0)),
	RADI_LEIDO tinyint NOT NULL DEFAULT ((0)),
	RADI_CUENTAI varchar(20)  NULL,
	RADI_TIPO_DERI tinyint NOT NULL DEFAULT ((0)),
	LISTO varchar(2)  NULL,
	SGD_TMA_CODIGO smallint NULL,
	SGD_MTD_CODIGO smallint NULL,
	PAR_SERV_SECUE int NULL,
	SGD_FLD_CODIGO smallint NOT NULL DEFAULT ((0)),
	RADI_AGEND tinyint NULL,
	RADI_FECH_AGEND datetime NULL,
	RADI_FECH_DOC datetime NULL,
	SGD_DOC_SECUENCIA bigint NULL,
	SGD_PNUFE_CODI smallint NULL,
	SGD_EANU_CODIGO tinyint NULL,
	SGD_NOT_CODI smallint NULL,
	RADI_FECH_NOTIF datetime NULL,
	SGD_TDEC_CODIGO smallint NULL,
	SGD_APLI_CODI smallint NULL,
	RADI_NRR smallint DEFAULT ((0)),
	SGD_TTR_CODIGO smallint NOT NULL DEFAULT ((0)),
	USUA_DOC_ANTE varchar(14)  NULL,
	RADI_FECH_ANTETX datetime NULL,
	SGD_TRAD_CODIGO tinyint NULL,
	FECH_VCMTO datetime NULL,
	TDOC_VCMTO smallint NULL,
	SGD_TERMINO_REAL smallint NULL,
	ID_CONT tinyint NOT NULL DEFAULT ((1)),
	SGD_SPUB_CODIGO tinyint NOT NULL DEFAULT ((0)),
	ID_PAIS smallint NOT NULL DEFAULT ((170)),
        MEDIO_M varchar(15) NULL,
	SGD_TRES_CODIGO tinyint NULL,
        PRIMARY KEY (RADI_NUME_RADI )
)

CREATE TABLE SEC_BODEGA_EMPRESAS(
	id float NOT NULL
)

CREATE TABLE sec_ciu_ciudadano(
	id float NOT NULL
)

CREATE TABLE sec_dir_direcciones(
	id float NOT NULL
)

CREATE TABLE sec_oem_oempresas(
	id float NOT NULL
)

CREATE TABLE SEC_PRESTAMO(
	id float NOT NULL
)


CREATE TABLE SECR_TP1_999(
	id float NOT NULL
)


CREATE TABLE SECR_TP2_999(
	id float NOT NULL
)


CREATE TABLE SERIES(
	DEPE_CODI int NOT NULL,
	SERI_NUME int NOT NULL,
	SERI_TIPO tinyint NOT NULL,
	SERI_ANO smallint NOT NULL,
	DPTO_CODI smallint NOT NULL,
	BLOQ varchar(20)  NULL,
        PRIMARY KEY (DEPE_CODI ,SERI_TIPO ,SERI_ANO )
)

CREATE TABLE SGD_ACM_ACUSEMSG(
	SGD_MSG_CODI bigint NOT NULL,
	USUA_DOC varchar(14)  NOT NULL,
	SGD_MSG_LEIDO smallint NULL,
        PRIMARY KEY (SGD_MSG_CODI ,USUA_DOC )
)

CREATE TABLE SGD_ACTADD_ACTUALIADICIONAL(
	SGD_ACTADD_CODI smallint NOT NULL,
	SGD_APLI_CODI smallint NULL,
	SGD_INSTORF_CODI smallint NULL,
	SGD_ACTADD_QUERY varchar(500)  NULL,
	SGD_ACTADD_DESC varchar(150)  NULL,
PRIMARY KEY (SGD_ACTADD_CODI )
)

CREATE TABLE SGD_ADMIN_DEPE_HISTORICO(
	ADMIN_DEPE_HISTORICO_CODIGO bigint NOT NULL,
	USUARIO_CODIGO_ADMINISTRADOR bigint NOT NULL,
	DEPENDENCIA_CODIGO_ADMINISTRADOR smallint NOT NULL,
	USUARIO_DOCUMENTO_ADMINISTRADOR varchar(14)  NOT NULL,
	DEPENDENCIA_MODIFICADA smallint NOT NULL,
	ADMIN_OBSERVACION_CODIGO bigint NOT NULL,
	ADMIN_FECHA_EVENTO datetime NOT NULL,
        PRIMARY KEY (ADMIN_DEPE_HISTORICO_CODIGO )
)

CREATE TABLE SGD_ADMIN_DEPENDENCIA_ESTADO(
	CODIGO_ESTADO bigint NOT NULL,
	DESCRIPCION_ESTADO varchar(50)  NOT NULL,
        PRIMARY KEY (CODIGO_ESTADO )
)

CREATE TABLE SGD_ADMIN_OBSERVACION(
	CODIGO_OBSERVACION bigint NOT NULL,
	DESCRIPCION_OBSERVACION varchar(500)  NOT NULL,
        PRIMARY KEY (CODIGO_OBSERVACION )
)

CREATE TABLE SGD_ADMIN_USUA_HISTORICO(
	ADMIN_HISTORICO_CODIGO bigint NOT NULL,
	USUARIO_CODIGO_ADMINISTRADOR bigint NOT NULL,
	DEPENDENCIA_CODIGO_ADMINISTRADOR smallint NOT NULL,
	USUARIO_DOCUMENTO_ADMINISTRADOR varchar(14)  NOT NULL,
	USUARIO_CODIGO_MODIFICADO bigint NOT NULL,
	DEPENDENCIA_CODIGO_MODIFICADO smallint NOT NULL,
	USUARIO_DOCUMENTO_MODIFICADO varchar(14)  NOT NULL,
	ADMIN_OBSERVACION_CODIGO bigint NOT NULL,
	ADMIN_FECHA_EVENTO datetime NOT NULL,
        PRIMARY KEY(ADMIN_HISTORICO_CODIGO )
)

CREATE TABLE SGD_ADMIN_USUA_PERFILES(
	CODIGO_PERFIL bigint NOT NULL,
	DESCRIPCION_PERFIL varchar(200)  NOT NULL,
        PRIMARY KEY(CODIGO_PERFIL)
)

CREATE TABLE SGD_AGEN_AGENDADOS(
	SGD_AGEN_FECH datetime NULL,
	SGD_AGEN_OBSERVACION varchar(3000)  NULL,
	RADI_NUME_RADI bigint NOT NULL,
	USUA_DOC varchar(18)  NOT NULL,
	DEPE_CODI smallint NULL,
	SGD_AGEN_CODIGO int NULL,
	SGD_AGEN_FECHPLAZO datetime NULL,
	SGD_AGEN_ACTIVO int NULL
)

CREATE TABLE SGD_ANAR_ANEXARG(
	SGD_ANAR_CODI smallint NOT NULL,
	ANEX_CODIGO varchar(20)  NULL,
	SGD_ARGD_CODI smallint NULL,
	SGD_ANAR_ARGCOD smallint NULL,
        PRIMARY KEY (SGD_ANAR_CODI)
)

CREATE TABLE SGD_ANU_ANULADOS(
	SGD_ANU_ID smallint NULL,
	SGD_ANU_DESC varchar(250)  NULL,
	RADI_NUME_RADI bigint NULL,
	SGD_EANU_CODI int NULL,
	SGD_ANU_SOL_FECH datetime NULL,
	SGD_ANU_FECH datetime NULL,
	DEPE_CODI smallint NULL,
	USUA_DOC varchar(14)  NULL,
	USUA_CODI smallint NULL,
	DEPE_CODI_ANU smallint NULL,
	USUA_DOC_ANU varchar(14)  NULL,
	USUA_CODI_ANU smallint NULL,
	USUA_ANU_ACTA int NULL,
	SGD_ANU_PATH_ACTA varchar(200)  NULL,
	SGD_TRAD_CODIGO tinyint NULL,
	MOTIVO_ANULACION_CODIGO smallint
)

CREATE TABLE SGD_APER_ADMINPERFILES(
	SGD_APER_CODIGO tinyint NOT NULL,
	SGD_APER_DESCRIPCION varchar(20)  NULL,
        PRIMARY KEY (SGD_APER_CODIGO )
)

CREATE TABLE SGD_APLFAD_PLICFUNADI(
	SGD_APLFAD_CODI smallint NOT NULL,
	SGD_APLI_CODI smallint NULL,
	SGD_APLFAD_MENU varchar(150)  NOT NULL,
	SGD_APLFAD_LK1 varchar(150)  NOT NULL,
	SGD_APLFAD_DESC varchar(150)  NOT NULL,
        PRIMARY KEY (SGD_APLFAD_CODI)
)

CREATE TABLE SGD_APLI_APLINTEGRA(
	SGD_APLI_CODI smallint NOT NULL,
	SGD_APLI_DESCRIP varchar(150)  NULL,
	SGD_APLI_LK1DESC varchar(150)  NULL,
	SGD_APLI_LK1 varchar(150)  NULL,
	SGD_APLI_LK2DESC varchar(150)  NULL,
	SGD_APLI_LK2 varchar(150)  NULL,
	SGD_APLI_LK3DESC varchar(150)  NULL,
	SGD_APLI_LK3 varchar(150)  NULL,
	SGD_APLI_LK4DESC varchar(150)  NULL,
	SGD_APLI_LK4 varchar(150)  NULL,
        PRIMARY KEY(SGD_APLI_CODI )
)

CREATE TABLE SGD_APLMEN_APLIMENS(
	SGD_APLMEN_CODI smallint NOT NULL,
	SGD_APLI_CODI smallint NULL,
	SGD_APLMEN_REF varchar(20)  NULL,
	SGD_APLMEN_HACIAORFEO smallint NULL,
	SGD_APLMEN_DESDEORFEO smallint NULL,
        PRIMARY KEY (SGD_APLMEN_CODI )
)

CREATE TABLE SGD_APLUS_PLICUSUA(
	SGD_APLUS_CODI smallint NOT NULL,
	SGD_APLI_CODI smallint NULL,
	USUA_DOC varchar(14)  NULL,
	SGD_TRAD_CODIGO tinyint NULL,
	SGD_APLUS_PRIORIDAD tinyint NULL,
        PRIMARY KEY (SGD_APLUS_CODI )
)

CREATE TABLE SGD_ARG_PLIEGO(
	SGD_ARG_CODIGO tinyint NOT NULL,
	SGD_ARG_DESC varchar(150)  NOT NULL
)


CREATE TABLE SGD_ARGD_ARGDOC(
	SGD_ARGD_CODI smallint NOT NULL,
	SGD_PNUFE_CODI smallint NULL,
	SGD_ARGD_TABLA varchar(100)  NULL,
	SGD_ARGD_TCODI varchar(100)  NULL,
	SGD_ARGD_TDES varchar(100)  NULL,
	SGD_ARGD_LLIST varchar(150)  NULL,
	SGD_ARGD_CAMPO varchar(100)  NULL,
        PRIMARY KEY(SGD_ARGD_CODI)
)


CREATE TABLE SGD_ARGUP_ARGUDOCTOP(
	SGD_ARGUP_CODI smallint NOT NULL,
	SGD_ARGUP_DESC varchar(50)  NULL,
	SGD_TPR_CODIGO smallint NULL,
        PRIMARY KEY (SGD_ARGUP_CODI )
)

CREATE TABLE SGD_CAMEXP_CAMPOEXPEDIENTE(
	SGD_CAMEXP_CODIGO smallint NOT NULL,
	SGD_CAMEXP_CAMPO varchar(30)  NOT NULL,
	SGD_PAREXP_CODIGO smallint NOT NULL,
	SGD_CAMEXP_FK int NOT NULL DEFAULT ((0)),
	SGD_CAMEXP_TABLAFK varchar(30)  NULL,
	SGD_CAMEXP_CAMPOFK varchar(30)  NULL,
	SGD_CAMEXP_CAMPOVALOR varchar(30)  NULL,
	SGD_CAMPEXP_ORDEN tinyint NULL,
        PRIMARY KEY (SGD_CAMEXP_CODIGO )
)

CREATE TABLE SGD_CARP_DESCRIPCION(
	SGD_CARP_DEPECODI smallint NOT NULL,
	SGD_CARP_TIPORAD tinyint NOT NULL,
	SGD_CARP_DESCR varchar(40)  NULL,
        PRIMARY KEY(SGD_CARP_DEPECODI ,	SGD_CARP_TIPORAD )
)

CREATE TABLE SGD_CAU_CAUSAL(
	SGD_CAU_CODIGO smallint NOT NULL,
	SGD_CAU_DESCRIP varchar(150)  NULL,
        PRIMARY KEY(SGD_CAU_CODIGO )
)

CREATE TABLE SGD_CAUX_CAUSALES(
	SGD_CAUX_CODIGO bigint NOT NULL,
	RADI_NUME_RADI bigint NULL,
	SGD_DCAU_CODIGO smallint NULL,
	SGD_DDCA_CODIGO smallint NULL,
	SGD_CAUX_FECHA datetime NULL,
	SGD_CAU_CODIGO smallint,
	USUA_DOC varchar(14)  NULL,
        PRIMARY KEY (SGD_CAUX_CODIGO )
)


CREATE TABLE SGD_CIU_CIUDADANO(
	TDID_CODI tinyint NULL,
	SGD_CIU_CODIGO int NOT NULL,
	SGD_CIU_NOMBRE varchar(150)  NULL,
	SGD_CIU_DIRECCION varchar(150)  NULL,
	SGD_CIU_APELL1 varchar(50)  NULL,
	SGD_CIU_APELL2 varchar(50)  NULL,
	SGD_CIU_TELEFONO varchar(50)  NULL,
	SGD_CIU_EMAIL varchar(50)  NULL,
	MUNI_CODI smallint NULL,
	DPTO_CODI smallint NULL,
	SGD_CIU_CEDULA varchar(13)  NULL,
	ID_CONT tinyint NOT NULL DEFAULT ((1)),
	ID_PAIS smallint NOT NULL DEFAULT ((170)),
        SGD_CIU_ACT boolean DEFAULT TRUE NOT NULL,
        PRIMARY KEY (SGD_CIU_CODIGO )
)

CREATE TABLE SGD_CLTA_CLSTARIF(
	SGD_FENV_CODIGO int NULL,
	SGD_CLTA_CODSER int NULL,
	SGD_TAR_CODIGO int NULL,
	SGD_CLTA_DESCRIP varchar(100)  NULL,
	SGD_CLTA_PESDES bigint NULL,
	SGD_CLTA_PESHAST bigint NULL
)

CREATE TABLE SGD_COB_CAMPOBLIGA(
	SGD_COB_CODI smallint NOT NULL,
	SGD_COB_DESC varchar(150)  NULL,
	SGD_COB_LABEL varchar(50)  NULL,
	SGD_TIDM_CODI smallint NULL,
        PRIMARY KEY (SGD_COB_CODI)
)

CREATE TABLE SGD_DCAU_CAUSAL(
	SGD_DCAU_CODIGO smallint NOT NULL,
	SGD_CAU_CODIGO smallint NULL,
	SGD_DCAU_ESTADO smallint,
	SGD_DCAU_DESCRIP varchar(150)  NULL,
        PRIMARY KEY(SGD_DCAU_CODIGO )
)

CREATE TABLE SGD_DDCA_DDSGRGDO(
	SGD_DDCA_CODIGO smallint NOT NULL,
	SGD_DCAU_CODIGO smallint NULL,
	PAR_SERV_SECUE int NULL,
	SGD_DDCA_DESCRIP varchar(150)  NULL,
        PRIMARY KEY (SGD_DDCA_CODIGO)
)

CREATE TABLE SGD_DEF_CONTACTOS(
	CTT_ID bigint NOT NULL,
	CTT_NOMBRE varchar(60)  NOT NULL,
	CTT_CARGO varchar(60)  NOT NULL,
	CTT_TELEFONO varchar(25)  NULL,
	CTT_ID_TIPO smallint NOT NULL,
	CTT_ID_EMPRESA bigint NOT NULL
)

CREATE TABLE SGD_DEF_CONTINENTES(
	ID_CONT tinyint NOT NULL,
	NOMBRE_CONT varchar(20)  NOT NULL,
        PRIMARY KEY (ID_CONT )
)

CREATE TABLE SGD_DEF_PAISES(
	ID_CONT tinyint NOT NULL DEFAULT ((1)),
	ID_PAIS smallint NOT NULL DEFAULT ((170)),
	NOMBRE_PAIS varchar(30)  NOT NULL,
        PRIMARY KEY(ID_CONT ,ID_PAIS )
)


CREATE TABLE SGD_DEVE_DEV_ENVIO(
	SGD_DEVE_CODIGO tinyint NOT NULL,
	SGD_DEVE_DESC varchar(150)  NOT NULL,
        PRIMARY KEY(SGD_DEVE_CODIGO )
)

CREATE TABLE SGD_DIR_DRECCIONES(
	SGD_DIR_CODIGO bigint NOT NULL,
	SGD_DIR_TIPO smallint NOT NULL,
	SGD_OEM_CODIGO int NULL,
	SGD_CIU_CODIGO int NULL,
	RADI_NUME_RADI bigint NULL,
	SGD_ESP_CODI int NULL,
	MUNI_CODI smallint NULL,
	DPTO_CODI smallint NULL,
	SGD_DIR_DIRECCION varchar(150)  NULL,
	SGD_DIR_TELEFONO varchar(50)  NULL,
	SGD_DIR_MAIL varchar(50)  NULL,
	SGD_SEC_CODIGO bigint NULL,
	SGD_TEMPORAL_NOMBRE varchar(150)  NULL,
	ANEX_CODIGO bigint NULL,
	SGD_ANEX_CODIGO varchar(20)  NULL,
	SGD_DIR_NOMBRE varchar(150)  NULL,
	SGD_DOC_FUN varchar(14)  NULL,
	SGD_DIR_NOMREMDES varchar(1000)  NULL,
	SGD_TRD_CODIGO tinyint NULL,
	SGD_DIR_TDOC tinyint NULL,
	SGD_DIR_DOC varchar(14)  NULL,
	ID_PAIS smallint NOT NULL DEFAULT ((170)),
	ID_CONT tinyint NOT NULL DEFAULT ((1)),
        MREC_CODI smallint,
        PRIMARY KEY (SGD_DIR_CODIGO )
)

CREATE TABLE SGD_DNUFE_DOCNUFE(
	SGD_DNUFE_CODI smallint NOT NULL,
	SGD_PNUFE_CODI smallint NULL,
	SGD_TPR_CODIGO smallint NULL,
	SGD_DNUFE_LABEL varchar(150)  NULL,
	TRTE_CODI tinyint NULL,
	SGD_DNUFE_MAIN varchar(1)  NULL,
	SGD_DNUFE_PATH varchar(150)  NULL,
	SGD_DNUFE_GERARQ varchar(10)  NULL,
	ANEX_TIPO_CODI smallint NULL,
        PRIMARY KEY (SGD_DNUFE_CODI )
)

CREATE TABLE SGD_EANU_ESTANULACION(
	SGD_EANU_DESC varchar(150)  NULL,
	SGD_EANU_CODI int NOT NULL,
        PRIMARY KEY (SGD_EANU_CODI )
)

CREATE TABLE SGD_EINV_INVENTARIO(
	SGD_EINV_CODIGO int NOT NULL,
	SGD_DEPE_NOMB varchar(400)  NULL,
	SGD_DEPE_CODI int NULL,
	SGD_EINV_EXPNUM varchar(18)  NULL,
	SGD_EINV_TITULO varchar(400)  NULL,
	SGD_EINV_UNIDAD int NULL,
	SGD_EINV_FECH datetime NULL,
	SGD_EINV_FECHFIN datetime NULL,
	SGD_EINV_RADICADOS varchar(40)  NULL,
	SGD_EINV_FOLIOS int NULL,
	SGD_EINV_NUNDOCU int NULL,
	SGD_EINV_NUNDOCUBODEGA int NULL,
	SGD_EINV_CAJA int NULL,
	SGD_EINV_CAJABODEGA int NULL,
	SGD_EINV_SRD int NULL,
	SGD_EINV_NOMSRD varchar(400)  NULL,
	SGD_EINV_SBRD int NULL,
	SGD_EINV_NOMSBRD varchar(400)  NULL,
	SGD_EINV_RETENCION varchar(400)  NULL,
	SGD_EINV_DISFINAL varchar(400)  NULL,
	SGD_EINV_UBICACION varchar(400)  NULL,
	SGD_EINV_OBSERVACION varchar(400)  NULL,
        PRIMARY KEY (SGD_EINV_CODIGO )
)


CREATE TABLE SGD_ARCH_DEPE
(
    SGD_ARCH_DEPE varchar(4),
    SGD_ARCH_EDIFICIO int,
    SGD_ARCH_ITEM int,
    SGD_ARCH_ID int NOT NULL,
    CONSTRAINT ID PRIMARY KEY(SGD_ARCH_ID)
);


CREATE TABLE "SGD_EIT_ITEMS"
(  "SGD_EIT_CODIGO" int ,
    "SGD_EIT_COD_PADRE" int ,
    "SGD_EIT_NOMBRE" varchar(50),
    "SGD_EIT_SIGLA" varchar(50),
    "ID_CONT" int,
    "ID_PAIS" int,
    "CODI_DPTO" int,
    "CODI_MUNI" int
) ;


CREATE TABLE SGD_ENT_ENTIDADES(
	SGD_ENT_NIT varchar(13)  NOT NULL,
	SGD_ENT_CODSUC varchar(4)  NOT NULL,
	SGD_ENT_PIAS int NULL,
	DPTO_CODI smallint NULL,
	MUNI_CODI smallint NULL,
	SGD_ENT_DESCRIP varchar(80)  NULL,
	SGD_ENT_DIRECCION varchar(50)  NULL,
	SGD_ENT_TELEFONO varchar(50)  NULL,
        PRIMARY KEY (SGD_ENT_NIT ,SGD_ENT_CODSUC )
)

CREATE TABLE SGD_ENVE_ENVIOESPECIAL(
	SGD_FENV_CODIGO int NULL,
	SGD_ENVE_VALORL varchar(30)  NULL,
	SGD_ENVE_VALORN varchar(30)  NULL,
	SGD_ENVE_DESC varchar(30)  NULL
)


CREATE TABLE SGD_ESTINST_ESTADOINSTANCIA(
	SGD_ESTINST_CODI smallint NOT NULL,
	SGD_APLI_CODI smallint NULL,
	SGD_INSTORF_CODI smallint NULL,
	SGD_ESTINST_VALOR smallint NULL,
	SGD_ESTINST_HABILITA tinyint NULL,
	SGD_ESTINST_MENSAJE varchar(100)  NULL,
        PRIMARY KEY (SGD_ESTINST_CODI)
)

CREATE TABLE SGD_EXP_EXPEDIENTE(
	SGD_EXP_NUMERO varchar(18)  NULL,
	RADI_NUME_RADI bigint NULL,
	SGD_EXP_FECH datetime NULL,
	SGD_EXP_FECH_MOD datetime NULL,
	DEPE_CODI smallint NULL,
	USUA_CODI smallint NULL,
	USUA_DOC varchar(15)  NULL,
	SGD_EXP_ESTADO tinyint NOT NULL DEFAULT ((0)),
	SGD_EXP_TITULO varchar(50)  NULL,
	SGD_EXP_ASUNTO varchar(150)  NULL,
	SGD_EXP_CARPETA varchar(30)  NULL,
	SGD_EXP_UFISICA varchar(20)  NULL,
	SGD_EXP_ISLA varchar(10)  NULL,
	SGD_EXP_ESTANTE varchar(10)  NULL,
	SGD_EXP_CAJA varchar(10)  NULL,
	SGD_EXP_FECH_ARCH datetime NULL,
	SGD_SRD_CODIGO smallint NULL,
	SGD_SBRD_CODIGO smallint NULL,
	SGD_FEXP_CODIGO smallint NOT NULL DEFAULT ((0)),
	SGD_EXP_SUBEXPEDIENTE int NULL,
	SGD_EXP_ARCHIVO tinyint NULL,
	SGD_EXP_UNICON tinyint NULL,
	SGD_EXP_FECHFIN datetime NULL,
	SGD_EXP_FOLIOS varchar(4)  NULL,
	SGD_EXP_RETE tinyint NULL,
	SGD_EXP_ENTREPA tinyint NULL,
	SGD_EXP_PRIVADO tinyint NULL,
	SGD_EXP_EDIFICIO varchar(40) NULL,
	SGD_EXP_CARRO varchar(4) NULL,
	RADI_USUA_ARCH varchar(15) NULL
)

CREATE TABLE SGD_FARS_FARISTAS(
	SGD_FARS_CODIGO int NOT NULL,
	SGD_PEXP_CODIGO int NULL,
	SGD_FEXP_CODIGOINI int NULL,
	SGD_FEXP_CODIGOFIN int NULL,
	SGD_FARS_DIASMINIMO smallint NULL,
	SGD_FARS_DIASMAXIMO smallint NULL,
	SGD_FARS_DESC varchar(100)  NULL,
	SGD_TRAD_CODIGO tinyint NULL,
	SGD_SRD_CODIGO smallint NULL,
	SGD_SBRD_CODIGO smallint NULL,
	SGD_FARS_TIPIFICACION tinyint NULL,
	SGD_TPR_CODIGO int NULL,
	SGD_FARS_AUTOMATICO int NULL,
	SGD_FARS_ROLGENERAL int NULL,
        PRIMARY KEY(SGD_FARS_CODIGO )
)

CREATE TABLE SGD_FENV_FRMENVIO(
	SGD_FENV_CODIGO int NOT NULL,
	SGD_FENV_DESCRIP varchar(40)  NOT NULL,
	SGD_FENV_PLANILLA tinyint NOT NULL DEFAULT ((0)),
	SGD_FENV_ESTADO tinyint NOT NULL DEFAULT ((1)),
	SGD_FENV_PORC DOUBLE,
        PRIMARY KEY (SGD_FENV_CODIGO)
)

CREATE TABLE SGD_FEXP_FLUJOEXPEDIENTES(
	SGD_FEXP_CODIGO int NOT NULL,
	SGD_PEXP_CODIGO int NULL,
	SGD_FEXP_ORDEN smallint NULL,
	SGD_FEXP_TERMINOS smallint NULL,
	SGD_FEXP_IMAGEN varchar(50)  NULL,
	SGD_FEXP_DESCRIP varchar(50)  NULL,
        PRIMARY KEY (SGD_FEXP_CODIGO)
)

CREATE TABLE SGD_FIRRAD_FIRMARADS(
	SGD_FIRRAD_ID bigint NOT NULL,
	RADI_NUME_RADI bigint NOT NULL,
	USUA_DOC varchar(14)  NOT NULL,
	SGD_FIRRAD_FIRMA image NULL,
	SGD_FIRRAD_FECHA datetime NOT NULL,
	SGD_FIRRAD_DOCSOLIC varchar(14)  NOT NULL,
	SGD_FIRRAD_FECHSOLIC datetime NOT NULL,
PRIMARY KEY 
(
	SGD_FIRRAD_ID 
)
)




--/****** Objeto:  Table SGD_FLD_FLUJODOC    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_FLD_FLUJODOC(
	SGD_FLD_CODIGO smallint NULL,
	SGD_FLD_DESC varchar(100)  NULL,
	SGD_TPR_CODIGO smallint NULL,
	SGD_FLD_IMAGEN varchar(50)  NULL,
	SGD_FLD_GRUPOWEB int NOT NULL DEFAULT ((0))
)




--/****** Objeto:  Table SGD_FUN_FUNCIONES    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_FUN_FUNCIONES(
	SGD_FUN_CODIGO smallint NOT NULL,
	SGD_FUN_DESCRIP varchar(530)  NULL,
	SGD_FUN_FECH_INI datetime NULL,
	SGD_FUN_FECH_FIN datetime NULL,
PRIMARY KEY 
(
	SGD_FUN_CODIGO 
)
)




--/****** Objeto:  Table SGD_HMTD_HISMATDOC    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_HMTD_HISMATDOC(
	SGD_HMTD_CODIGO int NOT NULL,
	SGD_HMTD_FECHA datetime NOT NULL,
	RADI_NUME_RADI bigint NOT NULL,
	USUA_CODI bigint NOT NULL,
	SGD_HMTD_OBSE varchar(600)  NOT NULL,
	USUA_DOC bigint NULL,
	DEPE_CODI smallint NULL,
	SGD_MTD_CODIGO smallint NULL,
PRIMARY KEY 
(
	SGD_HMTD_CODIGO 
)
)




--/****** Objeto:  Table SGD_INSTORF_INSTANCIASORFEO    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_INSTORF_INSTANCIASORFEO(
	SGD_INSTORF_CODI smallint NOT NULL,
	SGD_INSTORF_DESC varchar(100)  NULL,
PRIMARY KEY 
(
	SGD_INSTORF_CODI 
)
)




--/****** Objeto:  Table SGD_MASIVA_EXCEL    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_MASIVA_EXCEL(
	SGD_MASIVA_DEPENDENCIA smallint NULL,
	SGD_MASIVA_USUARIO bigint NULL,
	SGD_MASIVA_TIPORADICACION tinyint NULL,
	SGD_MASIVA_CODIGO bigint NOT NULL,
	SGD_MASIVA_RADICADA tinyint NULL,
	SGD_MASIVA_INTERVALO smallint NULL,
	SGD_MASIVA_RANGOINI varchar(15)  NULL,
	SGD_MASIVA_RANGOFIN varchar(15)  NULL,
PRIMARY KEY 
(
	SGD_MASIVA_CODIGO 
)
)




--/****** Objeto:  Table SGD_MAT_MATRIZ    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/




CREATE TABLE SGD_MAT_MATRIZ(
	SGD_MAT_CODIGO smallint NOT NULL,
	DEPE_CODI smallint NULL,
	SGD_FUN_CODIGO smallint NULL,
	SGD_PRC_CODIGO smallint NULL,
	SGD_PRD_CODIGO smallint NULL,
	SGD_MAT_FECH_INI datetime NULL,
	SGD_MAT_FECH_FIN datetime NULL,
	SGD_MAT_PESO_PRD numeric(18, 0) NULL,
PRIMARY KEY 
(
	SGD_MAT_CODIGO 
)
)


--/****** Objeto:  Table SGD_MPES_MDDPESO    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_MPES_MDDPESO(
	SGD_MPES_CODIGO int NOT NULL,
	SGD_MPES_DESCRIP varchar(10)  NULL,
PRIMARY KEY 
(
	SGD_MPES_CODIGO 
)
)




--/****** Objeto:  Table SGD_MRD_MATRIRD    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_MRD_MATRIRD(
	SGD_MRD_CODIGO smallint NOT NULL,
	DEPE_CODI smallint NOT NULL,
	SGD_SRD_CODIGO smallint NOT NULL,
	SGD_SBRD_CODIGO smallint NOT NULL,
	SGD_TPR_CODIGO smallint NOT NULL,
	SOPORTE varchar(10)  NULL,
	SGD_MRD_FECHINI datetime NULL,
	SGD_MRD_FECHFIN datetime NULL,
	SGD_MRD_ESTA varchar(10)  NULL,
PRIMARY KEY 
(
	SGD_MRD_CODIGO 
)
)




--/****** Objeto:  Table SGD_MSDEP_MSGDEP    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_MSDEP_MSGDEP(
	SGD_MSDEP_CODI bigint NOT NULL,
	DEPE_CODI smallint NOT NULL,
	SGD_MSG_CODI bigint NOT NULL,
PRIMARY KEY 
(
	SGD_MSDEP_CODI 
)
)


--/****** Objeto:  Table SGD_MSG_MENSAJE    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_MSG_MENSAJE(
	SGD_MSG_CODI bigint NOT NULL,
	SGD_TME_CODI smallint NOT NULL,
	SGD_MSG_DESC varchar(150)  NULL,
	SGD_MSG_FECHDESP datetime NOT NULL,
	SGD_MSG_URL varchar(150)  NOT NULL,
	SGD_MSG_VECES smallint NOT NULL,
	SGD_MSG_ANCHO int NOT NULL,
	SGD_MSG_LARGO int NOT NULL,
PRIMARY KEY 
(
	SGD_MSG_CODI 
)
)


CREATE TABLE SGD_MSA_MEDSOPARCHIVO
(
  SGD_MSA_CODIGO bigint,
  SGD_MSA_DESCRIP VARCHAR(20),
  SGD_MSA_ESTADO bigint,
  SGD_MSA_SIGLA VARCHAR(2),
    PRIMARY KEY (SGD_MSA_CODIGO)
)
;

--/****** Objeto:  Table SGD_MTD_MATRIZ_DOC    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/




CREATE TABLE SGD_MTD_MATRIZ_DOC(
	SGD_MTD_CODIGO smallint NOT NULL,
	SGD_MAT_CODIGO smallint NULL,
	SGD_TPR_CODIGO smallint NULL,
PRIMARY KEY 
(
	SGD_MTD_CODIGO 
)
);

CREATE TABLE SGD_MTD_METADATOS (
    SGD_MTD_CODIGO integer NOT NULL,
    SGD_MTD_NOMBRE varchar(32) NOT NULL,
    SGD_MTD_DESCRIP varchar(320) NOT NULL,
    SGD_MTD_ESTADO smallint DEFAULT 0 NOT NULL,
    SGD_SRD_CODIGO smallint,
    SGD_SBRD_CODIGO integer,
    SGD_TPR_CODIGO integer,
    SGD_MTD_OBLIG smallint DEFAULT 0 NOT NULL,
    PRIMARY KEY (SGD_MTD_CODIGO)
);

CREATE TABLE SGD_MMR_MATRIMETAEXPE (
    SGD_EXP_NUMERO varchar(18) NOT NULL,
    SGD_MTD_CODIGO integer NOT NULL,
    SGD_MMR_DATO varchar(400),
    PRIMARY KEY (SGD_EXP_NUMERO ,SGD_MTD_CODIGO )
);

CREATE TABLE SGD_MMR_MATRIMETARADI (
    RADI_NUME_RADI bigint NOT NULL,
    SGD_MTD_CODIGO integer NOT NULL,
    SGD_MMR_DATO varchar(400),
    PRIMARY KEY (RADI_NUME_RADI ,SGD_MTD_CODIGO )
);

--/****** Objeto:  Table SGD_NOT_NOTIFICACION    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_NOT_NOTIFICACION(
	SGD_NOT_CODI smallint NOT NULL,
	SGD_NOT_DESCRIP varchar(100)  NOT NULL,
PRIMARY KEY 
(
	SGD_NOT_CODI 
)
)




--/****** Objeto:  Table SGD_NTRD_NOTIFRAD    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_NTRD_NOTIFRAD(
	RADI_NUME_RADI bigint NOT NULL,
	SGD_NOT_CODI smallint NOT NULL,
	SGD_NTRD_NOTIFICADOR varchar(150)  NULL,
	SGD_NTRD_NOTIFICADO varchar(150)  NULL,
	SGD_NTRD_FECHA_NOT datetime NULL,
	SGD_NTRD_NUM_EDICTO int NULL,
	SGD_NTRD_FECHA_FIJA datetime NULL,
	SGD_NTRD_FECHA_DESFIJA datetime NULL,
	SGD_NTRD_OBSERVACIONES varchar(150)  NULL
)




--/****** Objeto:  Table SGD_OEM_OEMPRESAS    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_OEM_OEMPRESAS(
	SGD_OEM_CODIGO int NOT NULL,
	TDID_CODI tinyint NULL,
	SGD_OEM_OEMPRESA varchar(150)  NULL,
	SGD_OEM_REP_LEGAL varchar(150)  NULL,
	SGD_OEM_NIT varchar(14)  NULL,
	SGD_OEM_SIGLA varchar(50)  NULL,
	MUNI_CODI smallint NULL,
	DPTO_CODI smallint NULL,
	SGD_OEM_DIRECCION varchar(150)  NULL,
	SGD_OEM_TELEFONO varchar(50)  NULL,
	ID_CONT tinyint NOT NULL DEFAULT ((1)),
	ID_PAIS smallint NOT NULL DEFAULT ((170)),
        SGD_OEM_ACT boolean DEFAULT TRUE NOT NULL,
PRIMARY KEY 
(
	SGD_OEM_CODIGO 
)
)




--/****** Objeto:  Table SGD_PANU_PERANULADOS    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_PANU_PERANULADOS(
	SGD_PANU_CODI smallint NOT NULL,
	SGD_PANU_DESC varchar(200)  NULL,
PRIMARY KEY 
(
	SGD_PANU_CODI 
)
)




--/****** Objeto:  Table SGD_PARAMETRO    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_PARAMETRO(
	PARAM_NOMB varchar(30)  NOT NULL,
	PARAM_CODI int NOT NULL,
	PARAM_VALOR varchar(100)  NOT NULL,
PRIMARY KEY 
(
	PARAM_NOMB ,
	PARAM_CODI 
)
)




--/****** Objeto:  Table SGD_PAREXP_PARAMEXPEDIENTE    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_PAREXP_PARAMEXPEDIENTE(
	SGD_PAREXP_CODIGO smallint NOT NULL,
	DEPE_CODI smallint NOT NULL,
	SGD_PAREXP_TABLA varchar(30)  NOT NULL,
	SGD_PAREXP_ETIQUETA varchar(15)  NOT NULL,
	SGD_PAREXP_ORDEN tinyint NULL,
	SGD_PAREXP_EDITABLE tinyint NULL,
PRIMARY KEY 
(
	SGD_PAREXP_CODIGO 
)
)




--/****** Objeto:  Table SGD_PEXP_PROCEXPEDIENTES    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_PEXP_PROCEXPEDIENTES(
	SGD_PEXP_CODIGO int NOT NULL,
	SGD_PEXP_DESCRIP varchar(100)  NULL,
	SGD_PEXP_TERMINOS int NOT NULL DEFAULT ((0)),
	SGD_SRD_CODIGO smallint NULL,
	SGD_SBRD_CODIGO smallint NULL,
	SGD_PEXP_AUTOMATICO tinyint NOT NULL DEFAULT ((1)),
	SGD_PEXP_TIENEFLUJO tinyint NOT NULL DEFAULT ((0)),
PRIMARY KEY 
(
	SGD_PEXP_CODIGO 
)
)




--/****** Objeto:  Table SGD_PNUFE_PROCNUMFE    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_PNUFE_PROCNUMFE(
	SGD_PNUFE_CODI smallint NOT NULL,
	SGD_TPR_CODIGO smallint NULL,
	SGD_PNUFE_DESCRIP varchar(150)  NULL,
	SGD_PNUFE_SERIE varchar(50)  NULL,
PRIMARY KEY 
(
	SGD_PNUFE_CODI 
)
)




--/****** Objeto:  Table SGD_PNUN_PROCENUM    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_PNUN_PROCENUM(
	SGD_PNUN_CODI smallint NOT NULL,
	SGD_PNUFE_CODI smallint NULL,
	DEPE_CODI smallint NULL,
	SGD_PNUN_PREPONE varchar(50)  NULL,
PRIMARY KEY 
(
	SGD_PNUN_CODI 
)
)




--/****** Objeto:  Table SGD_PRC_PROCESO    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_PRC_PROCESO(
	SGD_PRC_CODIGO smallint NOT NULL,
	SGD_PRC_DESCRIP varchar(150)  NULL,
	SGD_PRC_FECH_INI datetime NULL,
	SGD_PRC_FECH_FIN datetime NULL,
PRIMARY KEY 
(
	SGD_PRC_CODIGO 
)
)




--/****** Objeto:  Table SGD_PRD_PRCDMENTOS    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_PRD_PRCDMENTOS(
	SGD_PRD_CODIGO smallint NOT NULL,
	SGD_PRD_DESCRIP varchar(200)  NULL,
	SGD_PRD_FECH_INI datetime NULL,
	SGD_PRD_FECH_FIN datetime NULL,
PRIMARY KEY 
(
	SGD_PRD_CODIGO 
)
)




--/****** Objeto:  Table SGD_RDF_RETDOCF    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_RDF_RETDOCF(
	SGD_MRD_CODIGO smallint NOT NULL,
	RADI_NUME_RADI bigint NOT NULL,
	DEPE_CODI smallint NOT NULL,
	USUA_CODI bigint NOT NULL,
	USUA_DOC varchar(14)  NOT NULL,
	SGD_RDF_FECH datetime NOT NULL
)




--/****** Objeto:  Table SGD_RENV_REGENVIO    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_RENV_REGENVIO(
	SGD_RENV_CODIGO int NOT NULL,
	SGD_FENV_CODIGO int NULL,
	SGD_RENV_FECH datetime NULL,
	RADI_NUME_SAL bigint NULL,
	SGD_RENV_DESTINO varchar(150)  NULL,
	SGD_RENV_TELEFONO varchar(50)  NULL,
	SGD_RENV_MAIL varchar(150)  NULL,
	SGD_RENV_PESO varchar(10)  NULL,
	SGD_RENV_VALOR varchar(10)  NULL,
	SGD_RENV_CERTIFICADO tinyint NULL,
	SGD_RENV_ESTADO tinyint NULL,
	USUA_DOC bigint NULL,
	SGD_RENV_NOMBRE varchar(100)  NULL,
	SGD_REM_DESTINO tinyint NOT NULL DEFAULT ((0)),
	SGD_DIR_CODIGO bigint NULL,
	SGD_RENV_PLANILLA varchar(8)  NULL,
	SGD_RENV_FECH_SAL datetime NULL,
	DEPE_CODI smallint NULL,
	SGD_DIR_TIPO smallint NOT NULL DEFAULT ((0)),
	RADI_NUME_GRUPO bigint NULL,
	SGD_RENV_DIR varchar(100)  NULL,
	SGD_RENV_DEPTO varchar(30)  NULL,
	SGD_RENV_MPIO varchar(30)  NULL,
	SGD_RENV_TEL varchar(20)  NULL,
	SGD_RENV_CANTIDAD smallint NOT NULL DEFAULT ((0)),
	SGD_RENV_TIPO tinyint NOT NULL DEFAULT ((0)),
	SGD_RENV_OBSERVA varchar(200)  NULL,
	SGD_RENV_GRUPO bigint NULL,
	SGD_DEVE_CODIGO tinyint NULL,
	SGD_DEVE_FECH datetime NULL,
	SGD_RENV_VALORTOTAL varchar(14)  NOT NULL DEFAULT ('0'),
	SGD_RENV_VALISTAMIENTO varchar(10)  NOT NULL DEFAULT ('0'),
	SGD_RENV_VDESCUENTO varchar(10)  NOT NULL DEFAULT ('0'),
	SGD_RENV_VADICIONAL varchar(14)  NOT NULL DEFAULT ('0'),
	SGD_DEPE_GENERA smallint NULL,
	SGD_RENV_PAIS varchar(30)  NOT NULL DEFAULT ('Colombia')
)




--/****** Objeto:  Table SGD_RFAX_RESERVAFAX    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_RFAX_RESERVAFAX(
	SGD_RFAX_CODIGO bigint NULL,
	SGD_RFAX_FAX varchar(30)  NULL,
	USUA_LOGIN varchar(30)  NULL,
	SGD_RFAX_FECH datetime NULL,
	SGD_RFAX_FECHRADI datetime NULL,
	RADI_NUME_RADI bigint NULL,
	SGD_RFAX_OBSERVA varchar(500)  NULL
)




--/****** Objeto:  Table SGD_RMR_RADMASIVRE    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/




CREATE TABLE SGD_RMR_RADMASIVRE(
	SGD_RMR_GRUPO bigint NOT NULL,
	SGD_RMR_RADI bigint NOT NULL,
PRIMARY KEY 
(
	SGD_RMR_GRUPO ,
	SGD_RMR_RADI 
)
)


--/****** Objeto:  Table SGD_SAN_SANCIONADOS    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_SAN_SANCIONADOS(
	SGD_SAN_REF varchar(20)  NOT NULL,
	SGD_SAN_DECISION varchar(60)  NULL,
	SGD_SAN_CARGO varchar(50)  NULL,
	SGD_SAN_EXPEDIENTE varchar(20)  NULL,
	SGD_SAN_TIPO_SANCION varchar(50)  NULL,
	SGD_SAN_PLAZO varchar(100)  NULL,
	SGD_SAN_VALOR numeric(18, 0) NULL,
	SGD_SAN_RADICACION varchar(15)  NULL,
	SGD_SAN_FECHA_RADICADO datetime NULL,
	SGD_SAN_VALORLETRAS varchar(1000)  NULL,
	SGD_SAN_NOMBREEMPRESA varchar(160)  NULL,
	SGD_SAN_MOTIVOS varchar(160)  NULL,
	SGD_SAN_SECTORES varchar(160)  NULL,
	SGD_SAN_PADRE varchar(15)  NULL,
	SGD_SAN_FECHA_PADRE datetime NULL,
	SGD_SAN_NOTIFICADO varchar(100)  NULL,
PRIMARY KEY 
(
	SGD_SAN_REF 
)
)




--/****** Objeto:  Table SGD_SBRD_SUBSERIERD    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_SBRD_SUBSERIERD(
	SGD_SRD_CODIGO smallint NOT NULL,
	SGD_SBRD_CODIGO smallint NOT NULL,
	SGD_SBRD_DESCRIP varchar(200)  NOT NULL,
	SGD_SBRD_FECHINI datetime NOT NULL,
	SGD_SBRD_FECHFIN datetime NOT NULL,
	SGD_SBRD_TIEMAG smallint NULL,
	SGD_SBRD_TIEMAC smallint NULL,
	SGD_SBRD_DISPFIN varchar(50)  NULL,
	SGD_SBRD_SOPORTE bigint  NULL,
	SGD_SBRD_PROCEDI varchar(200)  NULL,
	SGD_MTD_CODIGO integer,
PRIMARY KEY 
(
	SGD_SRD_CODIGO ,
	SGD_SBRD_CODIGO 
)
)




--/****** Objeto:  Table SGD_SED_SEDE    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_SED_SEDE(
	SGD_SED_CODI smallint NOT NULL,
	SGD_SED_DESC varchar(50)  NULL,
	SGD_TPR_CODIGO smallint NULL,
PRIMARY KEY 
(
	SGD_SED_CODI 
)
)




--/****** Objeto: Table SGD_NOH_NOHABILES    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_NOH_NOHABILES(
	NOH_FECHA datetime NOT NULL
)



--/****** Objeto:  Table SGD_SENUF_SECNUMFE    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_SENUF_SECNUMFE(
	SGD_SENUF_CODI smallint NOT NULL,
	SGD_PNUFE_CODI smallint NULL,
	DEPE_CODI int NULL,
	SGD_SENUF_SEC varchar(50)  NULL,
PRIMARY KEY 
(
	SGD_SENUF_CODI 
)
)




--/****** Objeto:  Table SGD_SEXP_SECEXPEDIENTES    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_SEXP_SECEXPEDIENTES(
	SGD_EXP_NUMERO varchar(18)  NOT NULL,
	SGD_SRD_CODIGO int NULL,
	SGD_SBRD_CODIGO int NULL,
	SGD_SEXP_SECUENCIA int NULL,
	DEPE_CODI smallint NULL,
	USUA_DOC varchar(15)  NULL,
	SGD_SEXP_FECH datetime NULL,
	SGD_FEXP_CODIGO int NULL,
	SGD_SEXP_ANO smallint NULL,
	USUA_DOC_RESPONSABLE varchar(18)  NULL,
	SGD_SEXP_PAREXP1 varchar(250)  NULL,
	SGD_SEXP_PAREXP2 varchar(160)  NULL,
	SGD_SEXP_PAREXP3 varchar(160)  NULL,
	SGD_SEXP_PAREXP4 varchar(160)  NULL,
	SGD_SEXP_PAREXP5 varchar(160)  NULL,
	SGD_PEXP_CODIGO int NULL,
	SGD_EXP_FECH_ARCH datetime NULL,
	SGD_FLD_CODIGO smallint NULL,
	SGD_EXP_FECHFLUJOANT datetime NULL,
	SGD_MRD_CODIGO smallint NULL,
	SGD_EXP_SUBEXPEDIENTE bigint NULL,
        SGD_SEXP_NOMBRE varchar(64)  NULL,
        SGD_SEXP_ASUNTO varchar(250)  NULL,
        SGD_SEXP_NIVELSEG smallint NULL,
PRIMARY KEY 
(
	SGD_EXP_NUMERO 
)
)




--/****** Objeto:  Table SGD_SRD_SERIESRD    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_SRD_SERIESRD(
	SGD_SRD_CODIGO smallint NOT NULL,
	SGD_SRD_DESCRIP varchar(70)  NOT NULL,
	SGD_SRD_FECHINI datetime NOT NULL,
	SGD_SRD_FECHFIN datetime NOT NULL,
PRIMARY KEY 
(
	SGD_SRD_CODIGO 
)
)




--/****** Objeto:  Table SGD_TAR_TARIFAS    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_TAR_TARIFAS(
	SGD_FENV_CODIGO int NULL,
	SGD_TAR_CODSER int NULL,
	SGD_TAR_CODIGO int NULL,
	SGD_TAR_VALENV1 bigint NULL,
	SGD_TAR_VALENV2 bigint NULL,
	SGD_TAR_VALENV1G1 bigint NULL,
	SGD_CLTA_CODSER int NULL,
	SGD_TAR_VALENV2G2 bigint NULL,
	SGD_CLTA_DESCRIP varchar(100)  NULL
)




--/****** Objeto:  Table SGD_TDEC_TIPODECISION    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_TDEC_TIPODECISION(
	SGD_APLI_CODI smallint NOT NULL,
	SGD_TDEC_CODIGO smallint NOT NULL,
	SGD_TDEC_DESCRIP varchar(150)  NULL,
	SGD_TDEC_SANCIONAR tinyint NULL,
	SGD_TDEC_FIRMEZA tinyint NULL,
	SGD_TDEC_VERSANCION tinyint NULL,
	SGD_TDEC_SHOWMENU tinyint NULL,
	SGD_TDEC_UPDNOTIF tinyint NULL,
PRIMARY KEY 
(
	SGD_TDEC_CODIGO 
)
)




--/****** Objeto:  Table SGD_TID_TIPDECISION    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_TID_TIPDECISION(
	SGD_TID_CODI smallint NOT NULL,
	SGD_TID_DESC varchar(150)  NULL,
	SGD_TPR_CODIGO smallint NULL,
	SGD_PEXP_CODIGO int NULL,
	SGD_TPR_CODIGOP tinyint NULL,
PRIMARY KEY 
(
	SGD_TID_CODI 
)
)




--/****** Objeto:  Table SGD_TIDM_TIDOCMASIVA    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_TIDM_TIDOCMASIVA(
	SGD_TIDM_CODI smallint NOT NULL,
	SGD_TIDM_DESC varchar(150)  NULL,
PRIMARY KEY 
(
	SGD_TIDM_CODI 
)
)




--/****** Objeto:  Table SGD_TIP3_TIPOTERCERO    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_TIP3_TIPOTERCERO(
	SGD_TIP3_CODIGO tinyint NOT NULL,
	SGD_DIR_TIPO smallint NULL,
	SGD_TIP3_NOMBRE varchar(15)  NULL,
	SGD_TIP3_DESC varchar(30)  NULL,
	SGD_TIP3_IMGPESTANA varchar(20)  NULL,
	SGD_TPR_TP1 tinyint NOT NULL DEFAULT ((0)),
	SGD_TPR_TP2 tinyint NOT NULL DEFAULT ((0)),
	SGD_TPR_TP3 tinyint NULL DEFAULT ((1)),
PRIMARY KEY 
(
	SGD_TIP3_CODIGO 
)
)




--/****** Objeto:  Table SGD_TMA_TEMAS    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_TMA_TEMAS(
	SGD_TMA_CODIGO smallint NOT NULL,
	SGD_PRC_CODIGO smallint NULL,
	SGD_TMA_DESCRIP varchar(150)  NULL,
PRIMARY KEY 
(
	SGD_TMA_CODIGO 
)
)




--/****** Objeto:  Table SGD_TMD_TEMADEPE    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/




CREATE TABLE SGD_TMD_TEMADEPE(
	ID int NOT NULL,
	SGD_TMA_CODIGO smallint NOT NULL,
	DEPE_CODI smallint NOT NULL,
PRIMARY KEY 
(
	ID 
)
)


--/****** Objeto:  Table SGD_TME_TIPMEN    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_TME_TIPMEN(
	SGD_TME_CODI smallint NOT NULL,
	SGD_TME_DESC varchar(150)  NULL,
PRIMARY KEY 
(
	SGD_TME_CODI 
)
)




--/****** Objeto:  Table SGD_TPR_TPDCUMENTO    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_TPR_TPDCUMENTO(
	SGD_TPR_CODIGO smallint NOT NULL,
	SGD_TPR_DESCRIP varchar(150)  NULL,
	SGD_TPR_TERMINO smallint NULL,
	SGD_TPR_TPUSO tinyint NULL,
	SGD_TPR_NUMERA varchar(1)  NULL,
	SGD_TPR_RADICA varchar(1)  NULL,
	SGD_TPR_TP1 tinyint NOT NULL DEFAULT ((0)),
	SGD_TPR_TP2 tinyint NOT NULL DEFAULT ((0)),
	SGD_TPR_ESTADO tinyint NULL,
	SGD_TERMINO_REAL smallint NULL,
	SGD_TPR_TP3 tinyint NULL,
PRIMARY KEY 
(
	SGD_TPR_CODIGO 
)
)




--/****** Objeto:  Table SGD_TRAD_TIPORAD    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_TRAD_TIPORAD(
	SGD_TRAD_CODIGO tinyint NOT NULL,
	SGD_TRAD_DESCR varchar(30)  NULL,
	SGD_TRAD_ICONO varchar(30)  NULL,
	SGD_TRAD_GENRADSAL tinyint NULL,
	SGD_TRAD_DIASBLOQUEO tinyint NOT NULL DEFAULT ((0)),
PRIMARY KEY 
(
	SGD_TRAD_CODIGO 
)
)




--/****** Objeto:  Table SGD_TRES_TPRESOLUCION    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_TRES_TPRESOLUCION(
	SGD_TRES_CODIGO tinyint NOT NULL,
	SGD_TRES_DESCRIP varchar(100)  NOT NULL,
	SGD_TPR_CODIGO smallint NULL,
PRIMARY KEY 
(
	SGD_TRES_CODIGO 
)
)




--/****** Objeto:  Table SGD_TTR_TRANSACCION    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_TTR_TRANSACCION(
	SGD_TTR_CODIGO smallint NOT NULL,
	SGD_TTR_DESCRIP varchar(100)  NOT NULL,
PRIMARY KEY 
(
	SGD_TTR_CODIGO 
)
)




--/****** Objeto:  Table SGD_USH_USUHISTORICO    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_USH_USUHISTORICO(
	SGD_USH_ADMCOD bigint NOT NULL,
	SGD_USH_ADMDEP int NOT NULL,
	SGD_USH_ADMDOC varchar(14)  NOT NULL,
	SGD_USH_USUCOD bigint NOT NULL,
	SGD_USH_USUDEP int NOT NULL,
	SGD_USH_USUDOC varchar(14)  NOT NULL,
	SGD_USH_MODCOD int NOT NULL,
	SGD_USH_FECHEVENTO datetime NOT NULL,
	SGD_USH_USULOGIN varchar(20)  NOT NULL
)




--/****** Objeto:  Table SGD_USM_USUMODIFICA    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE SGD_USM_USUMODIFICA(
	SGD_USM_MODCOD int NOT NULL,
	SGD_USM_MODDESCR varchar(60)  NOT NULL
)




--/****** Objeto:  Table TIPO_DOC_IDENTIFICACION    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE TIPO_DOC_IDENTIFICACION(
	TDID_CODI tinyint NOT NULL,
	TDID_DESC varchar(100)  NOT NULL,
PRIMARY KEY 
(
	TDID_CODI 
)
)




--/****** Objeto:  Table TIPO_REMITENTE    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE TIPO_REMITENTE(
	TRTE_CODI tinyint NOT NULL,
	TRTE_DESC varchar(100)  NOT NULL,
PRIMARY KEY 
(
	TRTE_CODI 
)
)




--/****** Objeto:  Table UBICACION_FISICA    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE UBICACION_FISICA(
	UBIC_DEPE_RADI int NOT NULL,
	UBIC_DEPE_ARCH int NULL,
	UBIC_INV_PISO varchar(2)  NOT NULL,
	UBIC_INV_PISO_DESC varchar(40)  NULL,
	UBIC_INV_ITEMSO varchar(40)  NULL,
	UBIC_INV_ITEMSN varchar(40)  NULL,
	UBIC_INV_ARCHIVADOR varchar(4)  NULL
)




--/****** Objeto:  Table USUARIO    Fecha de la secuencia de comandos: 08/01/2008 18:49:09 ******/






CREATE TABLE USUARIO(
	USUA_CODI smallint NOT NULL,
	DEPE_CODI smallint NOT NULL,
	USUA_LOGIN varchar(20)  NOT NULL,
	USUA_FECH_CREA datetime NOT NULL,
	USUA_PASW varchar(30)  NOT NULL,
	USUA_ESTA varchar(10)  NOT NULL,
	USUA_NOMB varchar(45)  NULL,
	PERM_RADI char(1)  NOT NULL DEFAULT ((0)),
	USUA_ADMIN char(1)  NOT NULL DEFAULT ((0)),
	USUA_NUEVO char(1)  NOT NULL DEFAULT ((0)),
	USUA_DOC varchar(14)  NOT NULL DEFAULT ('0'),
	CODI_NIVEL tinyint NOT NULL DEFAULT ((1)),
	USUA_SESION varchar(30)  NULL,
	USUA_FECH_SESION datetime NULL,
	USUA_EXT smallint NULL,
	USUA_NACIM datetime NULL,
	USUA_EMAIL varchar(50)  NULL,
	USUA_AT varchar(15)  NULL,
	USUA_PISO tinyint NULL,
	PERM_RADI_SAL int NOT NULL DEFAULT ((0)),
	USUA_ADMIN_ARCHIVO tinyint NOT NULL DEFAULT ((0)),
	USUA_MASIVA tinyint NOT NULL DEFAULT ((0)),
	USUA_PERM_DEV tinyint NOT NULL DEFAULT ((0)),
	USUA_PERM_NUMERA_RES varchar(1)  NULL,
	USUA_DOC_SUIP varchar(15)  NULL,
	USUA_PERM_NUMERADOC tinyint NULL,
	SGD_PANU_CODI smallint NULL,
	USUA_PRAD_TP1 tinyint NOT NULL DEFAULT ((0)),
	USUA_PRAD_TP2 tinyint NOT NULL DEFAULT ((0)),
	USUA_PERM_ENVIOS tinyint NOT NULL DEFAULT ((0)),
	USUA_PERM_MODIFICA tinyint NOT NULL DEFAULT ((0)),
	USUA_PERM_IMPRESION tinyint NOT NULL DEFAULT ((0)),
	SGD_APER_CODIGO tinyint NULL,
	USU_TELEFONO1 varchar(14)  NULL,
	USUA_ENCUESTA varchar(1)  NULL,
	SGD_PERM_ESTADISTICA tinyint NULL,
	USUA_PERM_SANCIONADOS tinyint NULL,
	USUA_ADMIN_SISTEMA tinyint NULL,
	USUA_PERM_TRD tinyint NULL,
	USUA_PERM_FIRMA tinyint NULL,
	USUA_PERM_PRESTAMO tinyint NULL,
	USUARIO_PUBLICO tinyint NULL,
	USUARIO_REASIGNAR tinyint NULL,
	USUA_PERM_NOTIFICA tinyint NULL,
	USUA_PERM_EXPEDIENTE int NULL,
	USUA_LOGIN_EXTERNO varchar(20)  NULL,
	ID_PAIS smallint NOT NULL DEFAULT ((170)),
	ID_CONT tinyint NOT NULL DEFAULT ((1)),
	PERM_TIPIF_ANEXO int NULL,
	PERM_VOBO varchar(1)  NOT NULL DEFAULT ('1'),
	PERM_ARCHI char(1)  NOT NULL DEFAULT ((1)),
	PERM_BORRAR_ANEXO int NULL,
	USUA_AUTH_LDAP int NULL,
	USUA_PERM_ADMINFLUJOS tinyint NOT NULL DEFAULT ((0)),
	USUA_ADM_PLANTILLA tinyint NOT NULL DEFAULT ((0)),
	USUA_PERM_INTERGAPPS tinyint NOT NULL DEFAULT ((0)),
	USUA_PRAD_TP3 tinyint NULL,
        USUA_PRAD_TPX smallint,
        USUA_PRAD_REPRAD smallint,
        USUA_TIMERELOAD  smallint NOT NULL DEFAULT 1, -- Valor minutos de recarga carpetas
        USUA_HABALERTAS  smallint NOT NULL DEFAULT 1, -- Habilita(1)/Deshabilita(0) la visualizacion de alertas
	USUA_PERM_REMIT_TERCERO smallint DEFAULT ((0)),
        usua_vobo_perm boolean DEFAULT FALSE NOT NULL,
        usua_super_perm smallint DEFAULT 0,
        mail_notif boolean default false,
        PRIMARY KEY (USUA_LOGIN )
)



CREATE TABLE sgd_matriz_nivelrad
(
    radi_nume_radi bigint,
    usua_login character varying(20)
);


CREATE TABLE sgd_carpeta_expediente
(
  sgd_carpeta_id integer NOT NULL,
  sgd_carpeta_csc integer NOT NULL,
  sgd_carpeta_numero integer NOT NULL,
  sgd_carpeta_descripcion varchar(500),
  sgd_exp_numero varchar(18) NOT NULL,
  sgd_carpeta_nfolios integer,
  PRIMARY KEY (sgd_carpeta_id)

);

CREATE TABLE sgd_exp_radcarpeta
(
  radi_nume_radi bigint NOT NULL,
  sgd_carpeta_id integer NOT NULL
);

CREATE TABLE sgd_matriz_nivelexp
(
  usua_login VARCHAR(15),
  sgd_exp_numero VARCHAR(18)
);

CREATE TABLE SGD_APLICACIONES
(    SGD_APLI_CODIGO integer NOT NULL,
    SGD_APLI_DESCRIP VARCHAR(30) NOT NULL,
    SGD_APLI_ESTADO smallint  NOT NULL DEFAULT ((1)),
    SGD_APLI_DEPE smallint NOT NULL,
    PRIMARY KEY (SGD_APLI_CODIGO)
) ;

CREATE TABLE MOTIVO_MODIFICACION
(
    MOTIVO_MODIFICACION_CODIGO integer NOT NULL,
    MOTIVO_MODIFICACION_DESCRIP VARCHAR(150) NOT NULL,
    PRIMARY KEY (MOTIVO_MODIFICACION_CODIGO)
);

CREATE TABLE IMPUSRREL (
    USUA_DOC VARCHAR(14) DEFAULT '0',
    DEPE_CODI smallint NOT NULL
);

CREATE TABLE MOTIVO_ANULACION
(
    MOTIVO_ANULACION_CODIGO integer NOT NULL,
    MOTIVO_ANULACION_DESCRIP VARCHAR(150) NOT NULL,
    PRIMARY KEY (MOTIVO_ANULACION_CODIGO)
);


ALTER TABLE ANEXOS  WITH CHECK ADD FOREIGN KEY(ANEX_CREADOR)
REFERENCES USUARIO (USUA_LOGIN)

ALTER TABLE ANEXOS_HISTORICO  WITH CHECK ADD FOREIGN KEY(ANEX_HIST_ANEX_CODI)
REFERENCES ANEXOS (ANEX_CODIGO)

ALTER TABLE ANEXOS_HISTORICO  WITH CHECK ADD FOREIGN KEY(ANEX_HIST_USUA)
REFERENCES USUARIO (USUA_LOGIN)

ALTER TABLE CARPETA_PER  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE DEPARTAMENTO  WITH CHECK ADD FOREIGN KEY(ID_CONT, ID_PAIS)
REFERENCES SGD_DEF_PAISES (ID_CONT, ID_PAIS)

ALTER TABLE DEPENDENCIA  WITH CHECK ADD FOREIGN KEY(DEPE_CODI_PADRE)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE DEPENDENCIA  WITH CHECK ADD FOREIGN KEY(ID_CONT, ID_PAIS, DPTO_CODI, MUNI_CODI)
REFERENCES MUNICIPIO (ID_CONT, ID_PAIS, DPTO_CODI, MUNI_CODI)

ALTER TABLE DEPENDENCIA_VISIBILIDAD  WITH CHECK ADD FOREIGN KEY(DEPENDENCIA_VISIBLE)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE DEPENDENCIA_VISIBILIDAD  WITH CHECK ADD FOREIGN KEY(DEPENDENCIA_OBSERVA)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE HIST_EVENTOS  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE HIST_EVENTOS  WITH CHECK ADD FOREIGN KEY(RADI_NUME_RADI)
REFERENCES RADICADO (RADI_NUME_RADI)

ALTER TABLE INFORMADOS  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE INFORMADOS  WITH CHECK ADD FOREIGN KEY(RADI_NUME_RADI)
REFERENCES RADICADO (RADI_NUME_RADI)

ALTER TABLE MUNICIPIO  WITH CHECK ADD FOREIGN KEY(ID_CONT, ID_PAIS, DPTO_CODI)
REFERENCES DEPARTAMENTO (ID_CONT, ID_PAIS, DPTO_CODI)

ALTER TABLE PRESTAMO  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE PRESTAMO  WITH CHECK ADD FOREIGN KEY(PRES_DEPE_ARCH)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE PRESTAMO  WITH CHECK ADD FOREIGN KEY(RADI_NUME_RADI)
REFERENCES RADICADO (RADI_NUME_RADI)

ALTER TABLE PRESTAMO  WITH CHECK ADD FOREIGN KEY(USUA_LOGIN_PRES)
REFERENCES USUARIO (USUA_LOGIN)

ALTER TABLE PRESTAMO  WITH CHECK ADD FOREIGN KEY(USUA_LOGIN_ACTU)
REFERENCES USUARIO (USUA_LOGIN)

ALTER TABLE RADICADO  WITH CHECK ADD FOREIGN KEY(ID_CONT, ID_PAIS, DPTO_CODI, MUNI_CODI)
REFERENCES MUNICIPIO (ID_CONT, ID_PAIS, DPTO_CODI, MUNI_CODI)

ALTER TABLE RADICADO  WITH CHECK ADD FOREIGN KEY(ESTA_CODI)
REFERENCES ESTADO (ESTA_CODI)

ALTER TABLE RADICADO  WITH CHECK ADD FOREIGN KEY(MREC_CODI)
REFERENCES MEDIO_RECEPCION (MREC_CODI)

ALTER TABLE RADICADO  WITH CHECK ADD FOREIGN KEY(PAR_SERV_SECUE)
REFERENCES PAR_SERV_SERVICIOS (PAR_SERV_SECUE)

ALTER TABLE RADICADO  WITH CHECK ADD FOREIGN KEY(SGD_APLI_CODI)
REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)

ALTER TABLE RADICADO  WITH CHECK ADD FOREIGN KEY(SGD_MTD_CODIGO)
REFERENCES SGD_MTD_MATRIZ_DOC (SGD_MTD_CODIGO)

ALTER TABLE RADICADO  WITH CHECK ADD FOREIGN KEY(SGD_NOT_CODI)
REFERENCES SGD_NOT_NOTIFICACION (SGD_NOT_CODI)

ALTER TABLE RADICADO  WITH CHECK ADD FOREIGN KEY(SGD_TDEC_CODIGO)
REFERENCES SGD_TDEC_TIPODECISION (SGD_TDEC_CODIGO)

ALTER TABLE RADICADO  WITH CHECK ADD FOREIGN KEY(SGD_TMA_CODIGO)
REFERENCES SGD_TMA_TEMAS (SGD_TMA_CODIGO)

ALTER TABLE RADICADO  WITH CHECK ADD FOREIGN KEY(TDID_CODI)
REFERENCES TIPO_DOC_IDENTIFICACION (TDID_CODI)

ALTER TABLE RADICADO  WITH CHECK ADD FOREIGN KEY(TRTE_CODI)
REFERENCES TIPO_REMITENTE (TRTE_CODI)

ALTER TABLE SGD_ACM_ACUSEMSG  WITH CHECK ADD FOREIGN KEY(SGD_MSG_CODI)
REFERENCES SGD_MSG_MENSAJE (SGD_MSG_CODI)

ALTER TABLE SGD_ACTADD_ACTUALIADICIONAL  WITH CHECK ADD FOREIGN KEY(SGD_APLI_CODI)
REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)

ALTER TABLE SGD_ACTADD_ACTUALIADICIONAL  WITH CHECK ADD FOREIGN KEY(SGD_INSTORF_CODI)
REFERENCES SGD_INSTORF_INSTANCIASORFEO (SGD_INSTORF_CODI)

ALTER TABLE SGD_ADMIN_DEPE_HISTORICO  WITH CHECK ADD FOREIGN KEY(DEPENDENCIA_MODIFICADA)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_ADMIN_USUA_HISTORICO  WITH CHECK ADD FOREIGN KEY(ADMIN_OBSERVACION_CODIGO)
REFERENCES SGD_ADMIN_OBSERVACION (CODIGO_OBSERVACION)

ALTER TABLE SGD_ADMIN_USUA_HISTORICO  WITH CHECK ADD FOREIGN KEY(DEPENDENCIA_CODIGO_ADMINISTRADOR)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_ADMIN_USUA_HISTORICO  WITH CHECK ADD FOREIGN KEY(DEPENDENCIA_CODIGO_MODIFICADO)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_AGEN_AGENDADOS  WITH CHECK ADD FOREIGN KEY(RADI_NUME_RADI)
REFERENCES RADICADO (RADI_NUME_RADI)

ALTER TABLE SGD_ANAR_ANEXARG  WITH CHECK ADD FOREIGN KEY(ANEX_CODIGO)
REFERENCES ANEXOS (ANEX_CODIGO)

ALTER TABLE SGD_ANAR_ANEXARG  WITH CHECK ADD FOREIGN KEY(SGD_ARGD_CODI)
REFERENCES SGD_ARGD_ARGDOC (SGD_ARGD_CODI)

ALTER TABLE SGD_ANU_ANULADOS  WITH CHECK ADD FOREIGN KEY(RADI_NUME_RADI)
REFERENCES RADICADO (RADI_NUME_RADI)

ALTER TABLE SGD_ANU_ANULADOS  WITH CHECK ADD FOREIGN KEY(SGD_EANU_CODI)
REFERENCES SGD_EANU_ESTANULACION (SGD_EANU_CODI)

ALTER TABLE SGD_APLFAD_PLICFUNADI  WITH CHECK ADD FOREIGN KEY(SGD_APLI_CODI)
REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)

ALTER TABLE SGD_APLMEN_APLIMENS  WITH CHECK ADD FOREIGN KEY(SGD_APLI_CODI)
REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)

ALTER TABLE SGD_APLUS_PLICUSUA  WITH CHECK ADD FOREIGN KEY(SGD_APLI_CODI)
REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)

ALTER TABLE SGD_CAMEXP_CAMPOEXPEDIENTE  WITH CHECK ADD FOREIGN KEY(SGD_PAREXP_CODIGO)
REFERENCES SGD_PAREXP_PARAMEXPEDIENTE (SGD_PAREXP_CODIGO)

ALTER TABLE SGD_CARP_DESCRIPCION  WITH CHECK ADD FOREIGN KEY(SGD_CARP_DEPECODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_CARP_DESCRIPCION  WITH CHECK ADD FOREIGN KEY(SGD_CARP_TIPORAD)
REFERENCES SGD_TRAD_TIPORAD (SGD_TRAD_CODIGO)

ALTER TABLE SGD_CAUX_CAUSALES  WITH CHECK ADD FOREIGN KEY(RADI_NUME_RADI)
REFERENCES RADICADO (RADI_NUME_RADI)

ALTER TABLE SGD_CAUX_CAUSALES  WITH CHECK ADD FOREIGN KEY(SGD_DCAU_CODIGO)
REFERENCES SGD_DCAU_CAUSAL (SGD_DCAU_CODIGO)

ALTER TABLE SGD_CAUX_CAUSALES  WITH CHECK ADD FOREIGN KEY(SGD_DDCA_CODIGO)
REFERENCES SGD_DDCA_DDSGRGDO (SGD_DDCA_CODIGO)

ALTER TABLE SGD_CIU_CIUDADANO  WITH CHECK ADD FOREIGN KEY(TDID_CODI)
REFERENCES TIPO_DOC_IDENTIFICACION (TDID_CODI)

ALTER TABLE SGD_CIU_CIUDADANO  WITH CHECK ADD FOREIGN KEY(ID_CONT, ID_PAIS, DPTO_CODI, MUNI_CODI)
REFERENCES MUNICIPIO (ID_CONT, ID_PAIS, DPTO_CODI, MUNI_CODI)

ALTER TABLE SGD_COB_CAMPOBLIGA  WITH CHECK ADD FOREIGN KEY(SGD_TIDM_CODI)
REFERENCES SGD_TIDM_TIDOCMASIVA (SGD_TIDM_CODI)

ALTER TABLE SGD_DCAU_CAUSAL  WITH CHECK ADD FOREIGN KEY(SGD_CAU_CODIGO)
REFERENCES SGD_CAU_CAUSAL (SGD_CAU_CODIGO)

ALTER TABLE SGD_DDCA_DDSGRGDO  WITH CHECK ADD FOREIGN KEY(PAR_SERV_SECUE)
REFERENCES PAR_SERV_SERVICIOS (PAR_SERV_SECUE)

ALTER TABLE SGD_DDCA_DDSGRGDO  WITH CHECK ADD FOREIGN KEY(SGD_DCAU_CODIGO)
REFERENCES SGD_DCAU_CAUSAL (SGD_DCAU_CODIGO)

ALTER TABLE SGD_DEF_PAISES  WITH CHECK ADD FOREIGN KEY(ID_CONT)
REFERENCES SGD_DEF_CONTINENTES (ID_CONT)

ALTER TABLE SGD_DIR_DRECCIONES  WITH CHECK ADD FOREIGN KEY(RADI_NUME_RADI)
REFERENCES RADICADO (RADI_NUME_RADI)

ALTER TABLE SGD_DIR_DRECCIONES  WITH CHECK ADD FOREIGN KEY(SGD_CIU_CODIGO)
REFERENCES SGD_CIU_CIUDADANO (SGD_CIU_CODIGO)

ALTER TABLE SGD_DIR_DRECCIONES  WITH CHECK ADD FOREIGN KEY(SGD_OEM_CODIGO)
REFERENCES SGD_OEM_OEMPRESAS (SGD_OEM_CODIGO)

ALTER TABLE SGD_DIR_DRECCIONES  WITH CHECK ADD FOREIGN KEY(ID_CONT, ID_PAIS, DPTO_CODI, MUNI_CODI)
REFERENCES MUNICIPIO (ID_CONT, ID_PAIS, DPTO_CODI, MUNI_CODI)

ALTER TABLE SGD_DNUFE_DOCNUFE  WITH CHECK ADD FOREIGN KEY(ANEX_TIPO_CODI)
REFERENCES ANEXOS_TIPO (ANEX_TIPO_CODI)

ALTER TABLE SGD_DNUFE_DOCNUFE  WITH CHECK ADD FOREIGN KEY(SGD_PNUFE_CODI)
REFERENCES SGD_PNUFE_PROCNUMFE (SGD_PNUFE_CODI)

ALTER TABLE SGD_DNUFE_DOCNUFE  WITH CHECK ADD FOREIGN KEY(SGD_TPR_CODIGO)
REFERENCES SGD_TPR_TPDCUMENTO (SGD_TPR_CODIGO)

ALTER TABLE SGD_DNUFE_DOCNUFE  WITH CHECK ADD FOREIGN KEY(TRTE_CODI)
REFERENCES TIPO_REMITENTE (TRTE_CODI)

ALTER TABLE SGD_ENVE_ENVIOESPECIAL  WITH CHECK ADD FOREIGN KEY(SGD_FENV_CODIGO)
REFERENCES SGD_FENV_FRMENVIO (SGD_FENV_CODIGO)

ALTER TABLE SGD_ESTINST_ESTADOINSTANCIA  WITH CHECK ADD FOREIGN KEY(SGD_APLI_CODI)
REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)

ALTER TABLE SGD_ESTINST_ESTADOINSTANCIA  WITH CHECK ADD FOREIGN KEY(SGD_INSTORF_CODI)
REFERENCES SGD_INSTORF_INSTANCIASORFEO (SGD_INSTORF_CODI)

ALTER TABLE SGD_EXP_EXPEDIENTE  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_EXP_EXPEDIENTE  WITH CHECK ADD FOREIGN KEY(RADI_NUME_RADI)
REFERENCES RADICADO (RADI_NUME_RADI)

ALTER TABLE SGD_FARS_FARISTAS  WITH CHECK ADD FOREIGN KEY(SGD_PEXP_CODIGO)
REFERENCES SGD_PEXP_PROCEXPEDIENTES (SGD_PEXP_CODIGO)

ALTER TABLE SGD_FEXP_FLUJOEXPEDIENTES  WITH CHECK ADD FOREIGN KEY(SGD_PEXP_CODIGO)
REFERENCES SGD_PEXP_PROCEXPEDIENTES (SGD_PEXP_CODIGO)

ALTER TABLE SGD_FIRRAD_FIRMARADS  WITH CHECK ADD FOREIGN KEY(RADI_NUME_RADI)
REFERENCES RADICADO (RADI_NUME_RADI)

ALTER TABLE SGD_HMTD_HISMATDOC  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_HMTD_HISMATDOC  WITH CHECK ADD FOREIGN KEY(RADI_NUME_RADI)
REFERENCES RADICADO (RADI_NUME_RADI)

ALTER TABLE SGD_HMTD_HISMATDOC  WITH CHECK ADD FOREIGN KEY(SGD_MTD_CODIGO)
REFERENCES SGD_MTD_MATRIZ_DOC (SGD_MTD_CODIGO)

ALTER TABLE SGD_MAT_MATRIZ  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_MAT_MATRIZ  WITH CHECK ADD FOREIGN KEY(SGD_FUN_CODIGO)
REFERENCES SGD_FUN_FUNCIONES (SGD_FUN_CODIGO)

ALTER TABLE SGD_MAT_MATRIZ  WITH CHECK ADD FOREIGN KEY(SGD_PRC_CODIGO)
REFERENCES SGD_PRC_PROCESO (SGD_PRC_CODIGO)

ALTER TABLE SGD_MAT_MATRIZ  WITH CHECK ADD FOREIGN KEY(SGD_PRD_CODIGO)
REFERENCES SGD_PRD_PRCDMENTOS (SGD_PRD_CODIGO)

ALTER TABLE SGD_MRD_MATRIRD  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_MRD_MATRIRD  WITH CHECK ADD FOREIGN KEY(SGD_SRD_CODIGO)
REFERENCES SGD_SRD_SERIESRD (SGD_SRD_CODIGO)

ALTER TABLE SGD_MRD_MATRIRD  WITH CHECK ADD FOREIGN KEY(SGD_TPR_CODIGO)
REFERENCES SGD_TPR_TPDCUMENTO (SGD_TPR_CODIGO)

ALTER TABLE SGD_MRD_MATRIRD  WITH CHECK ADD FOREIGN KEY(SGD_SRD_CODIGO, SGD_SBRD_CODIGO)
REFERENCES SGD_SBRD_SUBSERIERD (SGD_SRD_CODIGO, SGD_SBRD_CODIGO)

ALTER TABLE SGD_MSDEP_MSGDEP  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_MSDEP_MSGDEP  WITH CHECK ADD FOREIGN KEY(SGD_MSG_CODI)
REFERENCES SGD_MSG_MENSAJE (SGD_MSG_CODI)

ALTER TABLE SGD_MSG_MENSAJE  WITH CHECK ADD FOREIGN KEY(SGD_TME_CODI)
REFERENCES SGD_TME_TIPMEN (SGD_TME_CODI)

ALTER TABLE SGD_MTD_MATRIZ_DOC  WITH CHECK ADD FOREIGN KEY(SGD_MAT_CODIGO)
REFERENCES SGD_MAT_MATRIZ (SGD_MAT_CODIGO)

ALTER TABLE SGD_MTD_MATRIZ_DOC  WITH CHECK ADD FOREIGN KEY(SGD_TPR_CODIGO)
REFERENCES SGD_TPR_TPDCUMENTO (SGD_TPR_CODIGO)

ALTER TABLE SGD_NTRD_NOTIFRAD  WITH CHECK ADD FOREIGN KEY(RADI_NUME_RADI)
REFERENCES RADICADO (RADI_NUME_RADI)

ALTER TABLE SGD_OEM_OEMPRESAS  WITH CHECK ADD FOREIGN KEY(TDID_CODI)
REFERENCES TIPO_DOC_IDENTIFICACION (TDID_CODI)

ALTER TABLE SGD_OEM_OEMPRESAS  WITH CHECK ADD FOREIGN KEY(ID_CONT, ID_PAIS, DPTO_CODI, MUNI_CODI)
REFERENCES MUNICIPIO (ID_CONT, ID_PAIS, DPTO_CODI, MUNI_CODI)

ALTER TABLE SGD_PAREXP_PARAMEXPEDIENTE  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_PEXP_PROCEXPEDIENTES  WITH CHECK ADD FOREIGN KEY(SGD_SRD_CODIGO, SGD_SBRD_CODIGO)
REFERENCES SGD_SBRD_SUBSERIERD (SGD_SRD_CODIGO, SGD_SBRD_CODIGO)

ALTER TABLE SGD_PNUN_PROCENUM  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_PNUN_PROCENUM  WITH CHECK ADD FOREIGN KEY(SGD_PNUFE_CODI)
REFERENCES SGD_PNUFE_PROCNUMFE (SGD_PNUFE_CODI)

ALTER TABLE SGD_RDF_RETDOCF  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_RDF_RETDOCF  WITH CHECK ADD FOREIGN KEY(SGD_MRD_CODIGO)
REFERENCES SGD_MRD_MATRIRD (SGD_MRD_CODIGO)

ALTER TABLE SGD_RENV_REGENVIO  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_RENV_REGENVIO  WITH CHECK ADD FOREIGN KEY(SGD_DEVE_CODIGO)
REFERENCES SGD_DEVE_DEV_ENVIO (SGD_DEVE_CODIGO)

ALTER TABLE SGD_RENV_REGENVIO  WITH CHECK ADD FOREIGN KEY(SGD_DIR_CODIGO)
REFERENCES SGD_DIR_DRECCIONES (SGD_DIR_CODIGO)

ALTER TABLE SGD_SBRD_SUBSERIERD  WITH CHECK ADD FOREIGN KEY(SGD_SRD_CODIGO)
REFERENCES SGD_SRD_SERIESRD (SGD_SRD_CODIGO)

ALTER TABLE SGD_SEXP_SECEXPEDIENTES  WITH CHECK ADD FOREIGN KEY(SGD_PEXP_CODIGO)
REFERENCES SGD_PEXP_PROCEXPEDIENTES (SGD_PEXP_CODIGO)

ALTER TABLE SGD_TDEC_TIPODECISION  WITH CHECK ADD FOREIGN KEY(SGD_APLI_CODI)
REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)

ALTER TABLE SGD_TMA_TEMAS  WITH CHECK ADD FOREIGN KEY(SGD_PRC_CODIGO)
REFERENCES SGD_PRC_PROCESO (SGD_PRC_CODIGO)

ALTER TABLE SGD_TMD_TEMADEPE  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE SGD_TMD_TEMADEPE  WITH CHECK ADD FOREIGN KEY(SGD_TMA_CODIGO)
REFERENCES SGD_TMA_TEMAS (SGD_TMA_CODIGO)

ALTER TABLE USUARIO  WITH CHECK ADD FOREIGN KEY(DEPE_CODI)
REFERENCES DEPENDENCIA (DEPE_CODI)

ALTER TABLE USUARIO  WITH CHECK ADD FOREIGN KEY(SGD_APER_CODIGO)
REFERENCES SGD_APER_ADMINPERFILES (SGD_APER_CODIGO)

------------------------
--  ref constarinst for table SGD_MATRIZ_NIVELEXP
-----------------------
ALTER TABLE "SGD_MATRIZ_NIVELEXP" WITH CHECK ADD FOREIGN KEY (SGD_EXP_NUMERO)
      REFERENCES SGD_SEXP_SECEXPEDIENTES (SGD_EXP_NUMERO);

ALTER TABLE "SGD_MATRIZ_NIVELEXP" WITH CHECK ADD FOREIGN KEY(USUA_LOGIN)
      REFERENCES USUARIO (USUA_LOGIN);

------------------------
--  ref constarinst for table PRESTAMO
-----------------------

ALTER TABLE "PRESTAMO" ADD CONSTRAINT "FK_prest_exp" FOREIGN KEY ("SGD_EXP_NUMERO")
   REFERENCES "SGD_SEXP_SECEXPEDIENTES" ("SGD_EXP_NUMERO");

ALTER TABLE "PRESTAMO" ADD CONSTRAINT "FK_prest_carpexp" FOREIGN KEY ("SGD_CARPETA_ID")
   REFERENCES "SGD_CARPETA_EXPEDIENTE" ("SGD_CARPETA_ID");


ALTER TABLE  "SGD_SBRD_SUBSERIERD" ADD CONSTRAINT "fkey_sgd_sbrd_soporte" FOREIGN KEY ("SGD_SBRD_SOPORTE")
REFERENCES "SGD_MSA_MEDSOPARCHIVO"("SGD_MSA_CODIGO");

------------------------
--  ref constarinst for tables METADATOS
-----------------------

ALTER TABLE "SGD_MMR_MATRIMETAEXPE" ADD CONSTRAINT "FK_mmr_expediente" FOREIGN KEY ("SGD_EXP_NUMERO")
   REFERENCES "SGD_SEXP_SECEXPEDIENTES" ("SGD_EXP_NUMERO");
ALTER TABLE "SGD_MMR_MATRIMETAEXPE" ADD CONSTRAINT "FK_mmr_metadato" FOREIGN KEY ("SGD_MTD_CODIGO")
   REFERENCES "SGD_MTD_METADATOS" ("SGD_MTD_CODIGO");
ALTER TABLE "SGD_MMR_MATRIMETARADI" ADD CONSTRAINT "FK_mmr_metadato" FOREIGN KEY ("SGD_MTD_CODIGO")
   REFERENCES "SGD_MTD_METADATOS" ("SGD_MTD_CODIGO");
ALTER TABLE "SGD_MMR_MATRIMETARADI" ADD CONSTRAINT "FK_mmr_radicado" FOREIGN KEY ("RADI_NUME_RADI")
   REFERENCES "RADICADO" ("RADI_NUME_RADI");
ALTER TABLE "SGD_MTD_METADATOS" ADD CONSTRAINT "FK_mts_sbrd" FOREIGN KEY ("SGD_SRD_CODIGO", "SGD_SBRD_CODIGO")
   REFERENCES "SGD_SBRD_SUBSERIERD" ("SGD_SRD_CODIGO", "SGD_SBRD_CODIGO");
ALTER TABLE "SGD_MTD_METADATOS" ADD CONSTRAINT "FK_mts_tdoc" FOREIGN KEY ("SGD_TPR_CODIGO")
   REFERENCES "SGD_TPR_TPDCUMENTO" ("SGD_TPR_CODIGO");

------------------------------
--dia_sig_ant(): Recibe como parametros la fecha de inicio y la palabra Proximo ó Anterior, y devolverá el proximo o anterior dia habil.
-------------------------------------------

CREATE FUNCTION dia_sig_ant(@fechaini DATETIME, @proxant VARCHAR(10))
RETURNS DATETIME
AS
BEGIN
    DECLARE @intDay INT
    DECLARE @rtResult DATETIME
    SET @intDay = DATEPART(weekday,@fechaini)
    IF @proxant = 'Previous'
        IF @intDay = 1
            SET @rtResult = DATEADD(dd,-3,@fechaini)
        ELSE
            SET @rtResult = DATEADD(dd,-1,@fechaini)
    ELSE IF @proxant = 'Next'
        IF @intDay = 5
            SET @rtResult = DATEADD(dd,3,@fechaini)
        ELSE
            SET @rtResult = DATEADD(dd,1,@fechaini)
    ELSE
            SET @rtResult = @fechaini
    RETURN @rtResult
END

----------------------------------------------------
--sumadiashabiles(): Esta funcion recibe como parametros la fecha de inicio y el numero de dias habiles
--y retornara la fecha correspondiente teniendo en cuanta los dias festivos entre semana.
----------------------------------------------------

CREATE FUNCTION sumadiashabiles(@fecinicio datetime, @numdias integer)
RETURNS datetime
AS
BEGIN
    DECLARE @NextDay datetime
    DECLARE @Counter int
    DECLARE @diasem INT
    DECLARE @diasNH INT
    IF @numdias>0
    BEGIN
        SET @Counter=1
        SET @NextDay=CONVERT(datetime ,(CONVERT(char(10),@fecinicio,101)),101 )
        WHILE @Counter <= @numdias
        BEGIN
            SET @NextDay =dbo.dia_sig_ant(@NextDay,'Next' )
            SET @Counter=@Counter+1
        END
    END
    ELSE
        BEGIN
        SET @Counter=ABS(@numdias)
        SET @NextDay=CONVERT(datetime ,(CONVERT(char(10),@fecinicio,101)),101 )

        WHILE @Counter>0
        BEGIN
            SET @NextDay = dbo.dia_sig_ant(@NextDay,'Previous')
            SET @Counter=@Counter-1
        END
    END
    select @diasNH=    (select count(noh_fecha) from sgd_noh_nohabiles where noh_fecha between @fecinicio and @NextDay)
    set @NextDay=dateadd(dd,@diasNH,@NextDay)
    select @diasNH=    (select count(noh_fecha) from sgd_noh_nohabiles where noh_fecha = @NextDay)
    set @NextDay=dateadd(dd,@diasNH,@NextDay)
    SET @diasem = DATEPART(weekday,@NextDay)
    IF @diasem=6 or @diasem=7 begin
        SET @NextDay=dateadd(dd,2,@NextDay)
    END
    RETURN @NextDay
END

----------------------------------------------------------
--diashabiles():Funcion que recibe como parametros fecha inicial y fecha final
--y retorna dias habiles que han transcurrido entre dichas fechas teniendo en cuenta los festivos.
----------------------------------------------------------


CREATE FUNCTION diashabiles(@fecinicio datetime, @fecfin datetime)
RETURNS INT
AS
BEGIN
    DECLARE @fechaAnterior datetime
    DECLARE @dias INT
    DECLARE @diasNH INT
    SET @dias=0
    SET @fechaAnterior=@fecinicio
    SELECT @diasNH = (select count(noh_fecha) from sgd_noh_nohabiles where noh_fecha between @fecinicio and @fecfin)
    IF @fechaAnterior<=@fecfin
    BEGIN
        SET @fechaAnterior =dbo.dia_sig_ant(@fechaAnterior,'Next' )
        WHILE @fechaAnterior<=@fecfin
        BEGIN
            SET @fechaAnterior =dbo.dia_sig_ant(@fechaAnterior,'Next' )
            SET @dias=@dias-1
        END
        SET @dias=@dias+@diasNH
    END
    ELSE BEGIN
        SET @fechaAnterior=@fecinicio
        WHILE @fechaAnterior>@fecfin
        BEGIN
            SET @fechaAnterior = dbo.dia_sig_ant(@fechaAnterior,'Previous')
            SET @dias=@dias+1
        END
        SET @dias=@dias-@diasNH
    END
    RETURN @dias
END


insert into sec_bodega_empresa values(1969);
insert into sec_ciu_ciudadano values(0);
insert into sec_dir_direcciones values(0);
insert into sec_oem_oempresas values(1);
insert into sec_prestamo values(0);
insert into secr_tp1_999 values(0);
insert into secr_tp2_999 values(0);
