
-- crea secuencia de entidades:
CREATE SEQUENCE  "SEC_BODEGA_EMPRESAS"
INCREMENT BY 1
START WITH 1619
NOCACHE  NOORDER  NOCYCLE ;

-- crea secuencia de ciudadanos:
CREATE SEQUENCE  "SEC_CIU_CIUDADANO"
INCREMENT BY 1
START WITH 1
NOCACHE  NOORDER  NOCYCLE ;

-- crea secuencia de otras empresas:
CREATE SEQUENCE  "SEC_OEM_OEMPRESAS"
INCREMENT BY 1
START WITH 2
NOCACHE  NOORDER  NOCYCLE ;