
--TABLAS DE LA VERSIÓN 3.8.4 QUE FALTAN EN LA BASE DE DATOS DE LA VERSION 3.6

--crear tabla BORRAR_CARPETA_PERSONALIZADA 
CREATE TABLE "BORRAR_CARPETA_PERSONALIZADA" 
   (	"CARP_PER_CODI" NUMBER(2,0) NOT NULL ENABLE, 
	"CARP_PER_USU" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"CARP_PER_DESC" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_RAD_CARP_PER" PRIMARY KEY ("CARP_PER_CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS" ;
  
--crear tabla ENCUESTA
CREATE TABLE "ENCUESTA" 
   (	"USUA_DOC" VARCHAR2(14 BYTE) NOT NULL ENABLE, 
	"FECHA" TIMESTAMP (6), 
	"P1" VARCHAR2(100 BYTE), 
	"P2" VARCHAR2(100 BYTE), 
	"P3" VARCHAR2(100 BYTE), 
	"P4" VARCHAR2(100 BYTE), 
	"P5" VARCHAR2(100 BYTE), 
	"P6" VARCHAR2(100 BYTE), 
	"P7" VARCHAR2(100 BYTE), 
	"P7_CUAL" VARCHAR2(150 BYTE), 
	"P8" VARCHAR2(100 BYTE), 
	"P9" VARCHAR2(100 BYTE), 
	"P10" VARCHAR2(100 BYTE), 
	"P11" VARCHAR2(100 BYTE), 
	"P12" VARCHAR2(100 BYTE), 
	"P13" VARCHAR2(100 BYTE), 
	"P14" VARCHAR2(100 BYTE), 
	"P15" VARCHAR2(100 BYTE), 
	"P16" VARCHAR2(100 BYTE), 
	"P17" VARCHAR2(100 BYTE), 
	"P18" VARCHAR2(100 BYTE), 
	"P19" VARCHAR2(100 BYTE), 
	"P20" VARCHAR2(100 BYTE), 
	"P20_CUAL" VARCHAR2(150 BYTE), 
	"P21" VARCHAR2(100 BYTE), 
	"P22" VARCHAR2(100 BYTE), 
	"P23" VARCHAR2(100 BYTE), 
	"P24" VARCHAR2(100 BYTE), 
	"P25" VARCHAR2(100 BYTE), 
	 CONSTRAINT "PK_ENCUESTA" PRIMARY KEY ("USUA_DOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS" ;

--crear tabla PL_GENERADO_PLG
CREATE TABLE "PL_GENERADO_PLG" 
   (	"DEPE_CODI" NUMBER(7,0), 
	"RADI_NUME_RADI" NUMBER(15,0), 
	"PLT_CODI" NUMBER(4,0), 
	"PLG_CODI" NUMBER(4,0), 
	"PLG_COMENTARIOS" VARCHAR2(150 BYTE), 
	"PLG_ANALIZA" NUMBER(10,0), 
	"PLG_FIRMA" NUMBER(10,0), 
	"PLG_AUTORIZA" NUMBER(10,0), 
	"PLG_IMPRIME" NUMBER(10,0), 
	"PLG_ENVIA" NUMBER(10,0), 
	"PLG_ARCHIVO_TMP" VARCHAR2(150 BYTE), 
	"PLG_ARCHIVO_FINAL" VARCHAR2(150 BYTE), 
	"PLG_NOMBRE" VARCHAR2(30 BYTE), 
	"PLG_CREA" NUMBER(10,0) DEFAULT 0, 
	"PLG_AUTORIZA_FECH" TIMESTAMP (6), 
	"PLG_IMPRIME_FECH" TIMESTAMP (6), 
	"PLG_ENVIA_FECH" TIMESTAMP (6), 
	"PLG_CREA_FECH" TIMESTAMP (6), 
	"PLG_CREADOR" VARCHAR2(20 BYTE), 
	"PL_CODI" NUMBER(4,0), 
	"USUA_DOC" VARCHAR2(14 BYTE), 
	"SGD_REM_DESTINO" NUMBER(1,0) DEFAULT 0, 
	"RADI_NUME_SAL" NUMBER(15,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS" ;
  
--crear tabla PL_GENERADO_PLG
 CREATE TABLE "PL_TIPO_PLT" (
 "PLT_CODI" NUMBER(4,0) NOT NULL ENABLE, 
	"PLT_DESC" VARCHAR2(35 BYTE), 
 CONSTRAINT "PK_PL_TIPO_PLT" PRIMARY KEY ("PLT_CODI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ORFEODATATS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ORFEODATATS" ;
  
--crear tabla PL_GENERADO_PLG
CREATE TABLE "RETENCION_DOC_TMP" 
   (	"COD_SERIE" NUMBER(4,0), 
	"SERIE" VARCHAR2(100 BYTE), 
	"TIPOLOGIA_DOC" VARCHAR2(200 BYTE), 
	"COD_SUBSERIE" VARCHAR2(10 BYTE), 
	"SUBSERIE" VARCHAR2(100 BYTE), 
	"TIPOLOGIA_SUB" VARCHAR2(200 BYTE), 
	"DEPENDENCIA" NUMBER(7,0), 
	"NOM_DEPE" VARCHAR2(200 BYTE), 
	"ARCHIVO_GESTION" NUMBER(3,0), 
	"ARCHIVO_CENTRAL" NUMBER(3,0), 
	"DISPOSICION" VARCHAR2(100 BYTE), 
	"SOPORTE" VARCHAR2(20 BYTE), 
	"PROCEDIMIENTO" VARCHAR2(500 BYTE), 
	"TIPO_DOC" NUMBER(4,0), 
	"ERROR" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS" ;
  
  
--crear tabla PL_GENERADO_PLG
CREATE TABLE "SGD_AUDITORIA" 
   (	"USUA_DOC" VARCHAR2(50 BYTE), 
	"TIPO" VARCHAR2(20 BYTE), 
	"TABLA" VARCHAR2(50 BYTE), 
	"ISQL" VARCHAR2(1000 BYTE), 
	"FECHA" NUMBER(20,0), 
	"IP" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ORFEODATATS" ;
  
CREATE TABLE "SGD_TSOP_TIPOSOPORTE" 
   (	"SGD_TSOP_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"SGD_TSOP_DESCR" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"SGD_TSOP_DEPE_CODI" NUMBER(10,0), 
	"SGD_TSOP_USUA_CODI" NUMBER(4,0), 
	"SGD_TSOP_ESTADO" NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT "SGD_TSOP_TIPOSOPORTE_PK1" UNIQUE ("SGD_TSOP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS" ;
  
CREATE TABLE "SGD_SOP_SOPORTE" 
   (	"SGD_SOP_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"USUA_CODI" NUMBER(10,0) NOT NULL ENABLE, 
	"DEPE_CODI" NUMBER(10,0) NOT NULL ENABLE, 
	"SGD_SOP_COMENT" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"SGD_SOP_EST" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"SGD_TSOP_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"SGD_SOP_FECHAINI" DATE NOT NULL ENABLE, 
	"SGD_SOP_FECHAFIN" DATE, 
	 CONSTRAINT "SGD_SOP_SOPORTE_SGD_SOP_I_F0UQ" UNIQUE ("SGD_SOP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS"  ENABLE, 
	 CONSTRAINT "FK_SOP_SOPORTE_FK2" FOREIGN KEY ("SGD_TSOP_ID")
	  REFERENCES "SGD_TSOP_TIPOSOPORTE" ("SGD_TSOP_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS" ;
--crear tabla PL_GENERADO_PLG
CREATE TABLE "SGD_CSOP_COMENT" 
   (	"SGD_CSOP_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"SGD_SOP_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"SGD_CSOP_COMENT" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"USUA_CODI" NUMBER(10,0) NOT NULL ENABLE, 
	"DEPE_CODI" NUMBER(10,0) NOT NULL ENABLE, 
	"SGD_CSOP_FECHA" DATE NOT NULL ENABLE, 
	 CONSTRAINT "SGD_CSOP_COMENT_PK1_F0UQ" UNIQUE ("SGD_CSOP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS"  ENABLE, 
	 CONSTRAINT "FK_SOP_SOPORTE" FOREIGN KEY ("SGD_SOP_ID")
	  REFERENCES "SGD_SOP_SOPORTE" ("SGD_SOP_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS" ;
 
CREATE TABLE "SGD_EMPUS_EMPUSUARIO" 
   (	"SGD_EMPUS_CODIGO" NUMBER(5,0) NOT NULL ENABLE, 
	"SGD_EMPUS_ESTADO" CHAR(1 BYTE), 
	"USUA_LOGIN" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IDENTIFICADOR_EMPRESA" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_SGD_EMPUS_USUARIO" PRIMARY KEY ("SGD_EMPUS_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS"  ENABLE	 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS" ;

CREATE TABLE "SGD_LIP_LINKIP" 
   (	"SGD_LIP_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"SGD_LIP_IPINI" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SGD_LIP_IPFIN" VARCHAR2(20 BYTE), 
	"SGD_LIP_DIRINTRANET" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"DEPE_CODI" NUMBER(10,0) NOT NULL ENABLE, 
	"SGD_LIP_ARCH" VARCHAR2(70 BYTE), 
	"SGD_LIP_DIASCACHE" NUMBER(5,0), 
	"SGD_LIP_RUTAFTP" VARCHAR2(150 BYTE), 
	"SGD_LIP_SERVFTP" VARCHAR2(50 BYTE), 
	"SGD_LIP_USBD" VARCHAR2(20 BYTE), 
	"SGD_LIP_NOMBD" VARCHAR2(20 BYTE), 
	"SGD_LIP_PWDBD" VARCHAR2(20 BYTE), 
	"SGD_LIP_USFTP" VARCHAR2(20 BYTE), 
	"SGD_LIP_PWDFTP" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS" ;
  
CREATE TABLE "SGD_NFN_NOTIFIJACION" 
   (	"RADI_NUME_RADI" NUMBER NOT NULL ENABLE, 
	"SGD_TDF_CODIGO" NUMBER NOT NULL ENABLE, 
	"SGD_NFN_FECHNOTUSU" TIMESTAMP (6), 
	"SGD_NFN_FECHNOTEMP" TIMESTAMP (6), 
	"SGD_NFN_FECHFIUSU" TIMESTAMP (6), 
	"SGD_NFN_FECHFIEMP" TIMESTAMP (6), 
	"SGD_NFN_FECHDESFIUSU" TIMESTAMP (6), 
	"SGD_NFN_FECHDESFIEMP" TIMESTAMP (6), 
	"SGD_NFN_SSPDAPELA" VARCHAR2(2 BYTE), 
	 CONSTRAINT "SGD_NFN_NOTIFIJACION_PK" PRIMARY KEY ("RADI_NUME_RADI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ORFEODATATS" ;
  
CREATE TABLE "SGD_NOVEDAD_USUARIO" 
   (	"USUA_DOC" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOV_INFOR" VARCHAR2(255 BYTE), 
	"NOV_REASIG" VARCHAR2(255 BYTE), 
	"NOV_VOBO" VARCHAR2(255 BYTE), 
	"NOV_DEV" VARCHAR2(255 BYTE), 
	"NOV_ENTR" VARCHAR2(255 BYTE), 
	 CONSTRAINT "SGD_NOVEDAD_USUARIO_PKEY" PRIMARY KEY ("USUA_DOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ORFEODATATS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ORFEODATATS" ;
 
CREATE TABLE "SGD_PARAM_ADMIN" 
   (	"PARAM_CODIGO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PARAM_NOMBRE" VARCHAR2(255 BYTE), 
	"PARAM_DESC" VARCHAR2(255 BYTE), 
	"PARAM_VALOR" VARCHAR2(255 BYTE), 
	 CONSTRAINT "SGD_PARAM_ADMIN_PKEY" PRIMARY KEY ("PARAM_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ORFEODATATS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ORFEODATATS" ;
   
CREATE TABLE "SGD_TDF_TIPODEFALLOS" 
   (	"SGD_TDF_CODIGO" NUMBER NOT NULL ENABLE, 
	"SGD_TDF_NOMBRE_FALLO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "SGD_TDF_TIPODEFALLOS_PK" PRIMARY KEY ("SGD_TDF_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ORFEODATATS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ORFEODATATS" ;
 
   COMMENT ON COLUMN "SGD_CSOP_COMENT"."SGD_CSOP_ID" IS 'Identificacion del comentario realizado a un soporte';
   COMMENT ON COLUMN "SGD_CSOP_COMENT"."SGD_SOP_ID" IS 'No de identificacion del soporte al cual se le realiza el comentario';
   COMMENT ON COLUMN "SGD_CSOP_COMENT"."USUA_CODI" IS 'Codigo del usuario que realiza la transacción ';
   COMMENT ON COLUMN "SGD_CSOP_COMENT"."DEPE_CODI" IS 'Dependencia a la que pertenece el usuario que realiza la transacción';
   COMMENT ON COLUMN "SGD_SOP_SOPORTE"."SGD_SOP_ID" IS 'Identificador del numero del soporte';
   COMMENT ON COLUMN "SGD_SOP_SOPORTE"."USUA_CODI" IS 'Codigo del usaurio que crea el soporte';
   COMMENT ON COLUMN "SGD_SOP_SOPORTE"."DEPE_CODI" IS 'Dependencia del usuario que crea el soporte';
   COMMENT ON COLUMN "SGD_SOP_SOPORTE"."SGD_SOP_COMENT" IS 'comentario del soporte';
   COMMENT ON COLUMN "SGD_SOP_SOPORTE"."SGD_SOP_EST" IS 'Estado del soporte, especifica si esta con o sin respuesta';
   COMMENT ON COLUMN "SGD_SOP_SOPORTE"."SGD_TSOP_ID" IS 'Tabla relacionada con el tipo de soporte.';
   COMMENT ON COLUMN "SGD_SOP_SOPORTE"."SGD_SOP_FECHAINI" IS 'Fecha de inicio del soporte';
   COMMENT ON COLUMN "SGD_SOP_SOPORTE"."SGD_SOP_FECHAFIN" IS 'Fecha de finalización del proceso';
   COMMENT ON COLUMN "SGD_TSOP_TIPOSOPORTE"."SGD_TSOP_ID" IS 'Identificador del tipo de soporte que se secrea';
   
   
  