--------------------------------------------------------
-- Archivo creado  - martes-enero-12-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GRUPOPQR
--------------------------------------------------------

  CREATE TABLE "GRUPOPQR" 
   (	"ID" NUMBER(*,0), 
	"NOMBREGRUPO" VARCHAR2(100 BYTE), 
	"TABLAGRUPO" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into GRUPOPQR
SET DEFINE OFF;
Insert into GRUPOPQR (ID,NOMBREGRUPO,TABLAGRUPO,DESCRIPCION) values ('1','DATOS GENERALES',null,'libro de cartograf&iacute;a geol&oacute;gica');
Insert into GRUPOPQR (ID,NOMBREGRUPO,TABLAGRUPO,DESCRIPCION) values ('2','DATOS PERSONALES',null,'datos personales');
Insert into GRUPOPQR (ID,NOMBREGRUPO,TABLAGRUPO,DESCRIPCION) values ('3','DATOS DE CONTACTO',null,null);
Insert into GRUPOPQR (ID,NOMBREGRUPO,TABLAGRUPO,DESCRIPCION) values ('4','DATOS DE SEGURIDAD',null,null);
--------------------------------------------------------
--  DDL for Index SYS_C0014430
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0014430" ON "GRUPOPQR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GRUPOPQR
--------------------------------------------------------

  ALTER TABLE "GRUPOPQR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
